"""Sync configuracion final

Revision ID: 0d7158ce8ae4
Revises: 3748c6e1f016
Create Date: 2026-03-09 21:58:57.374843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d7158ce8ae4'
down_revision: Union[str, Sequence[str], None] = '3748c6e1f016'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permisos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_permiso', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='configuracion'
    )
    op.create_index(op.f('ix_configuracion_permisos_id'), 'permisos', ['id'], unique=False, schema='configuracion')
    op.create_index(op.f('ix_configuracion_permisos_nombre_permiso'), 'permisos', ['nombre_permiso'], unique=True, schema='configuracion')
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_rol', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='configuracion'
    )
    op.create_index(op.f('ix_configuracion_roles_id'), 'roles', ['id'], unique=False, schema='configuracion')
    op.create_index(op.f('ix_configuracion_roles_nombre_rol'), 'roles', ['nombre_rol'], unique=True, schema='configuracion')
    op.create_table('rol_permiso',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['configuracion.permisos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['configuracion.roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id'),
    schema='configuracion'
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cedula', sa.String(length=20), nullable=False),
    sa.Column('nombres', sa.String(length=100), nullable=False),
    sa.Column('apellidos', sa.String(length=100), nullable=False),
    sa.Column('correo', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['configuracion.roles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='configuracion'
    )
    op.create_index(op.f('ix_configuracion_usuarios_cedula'), 'usuarios', ['cedula'], unique=True, schema='configuracion')
    op.create_index(op.f('ix_configuracion_usuarios_correo'), 'usuarios', ['correo'], unique=True, schema='configuracion')
    op.create_index(op.f('ix_configuracion_usuarios_id'), 'usuarios', ['id'], unique=False, schema='configuracion')
    op.drop_constraint(op.f('personal_usuario_id_fkey'), 'personal', schema='administracion', type_='foreignkey')
    op.create_foreign_key(None, 'personal', 'usuarios', ['usuario_id'], ['id'], source_schema='administracion', referent_schema='configuracion', ondelete='SET NULL')
    op.drop_constraint(op.f('barrios_creado_por_id_fkey'), 'barrios', schema='catastro', type_='foreignkey')
    op.drop_constraint(op.f('barrios_actualizado_por_id_fkey'), 'barrios', schema='catastro', type_='foreignkey')
    op.create_foreign_key(None, 'barrios', 'usuarios', ['actualizado_por_id'], ['id'], source_schema='catastro', referent_schema='configuracion', ondelete='SET NULL')
    op.create_foreign_key(None, 'barrios', 'usuarios', ['creado_por_id'], ['id'], source_schema='catastro', referent_schema='configuracion', ondelete='SET NULL')
    op.drop_constraint(op.f('calles_creado_por_id_fkey'), 'calles', schema='catastro', type_='foreignkey')
    op.drop_constraint(op.f('calles_actualizado_por_id_fkey'), 'calles', schema='catastro', type_='foreignkey')
    op.create_foreign_key(None, 'calles', 'usuarios', ['actualizado_por_id'], ['id'], source_schema='catastro', referent_schema='configuracion', ondelete='SET NULL')
    op.create_foreign_key(None, 'calles', 'usuarios', ['creado_por_id'], ['id'], source_schema='catastro', referent_schema='configuracion', ondelete='SET NULL')
    op.drop_constraint(op.f('ciudadanos_creado_por_id_fkey'), 'ciudadanos', schema='catastro', type_='foreignkey')
    op.drop_constraint(op.f('ciudadanos_actualizado_por_id_fkey'), 'ciudadanos', schema='catastro', type_='foreignkey')
    op.create_foreign_key(None, 'ciudadanos', 'usuarios', ['actualizado_por_id'], ['id'], source_schema='catastro', referent_schema='configuracion', ondelete='SET NULL')
    op.create_foreign_key(None, 'ciudadanos', 'usuarios', ['creado_por_id'], ['id'], source_schema='catastro', referent_schema='configuracion', ondelete='SET NULL')
    op.drop_constraint(op.f('redes_creado_por_id_fkey'), 'redes', schema='catastro', type_='foreignkey')
    op.drop_constraint(op.f('redes_actualizado_por_id_fkey'), 'redes', schema='catastro', type_='foreignkey')
    op.create_foreign_key(None, 'redes', 'usuarios', ['actualizado_por_id'], ['id'], source_schema='catastro', referent_schema='configuracion', ondelete='SET NULL')
    op.create_foreign_key(None, 'redes', 'usuarios', ['creado_por_id'], ['id'], source_schema='catastro', referent_schema='configuracion', ondelete='SET NULL')
    op.drop_constraint(op.f('referencias_ciudadanos_actualizado_por_id_fkey'), 'referencias_ciudadanos', schema='catastro', type_='foreignkey')
    op.drop_constraint(op.f('referencias_ciudadanos_creado_por_id_fkey'), 'referencias_ciudadanos', schema='catastro', type_='foreignkey')
    op.create_foreign_key(None, 'referencias_ciudadanos', 'usuarios', ['actualizado_por_id'], ['id'], source_schema='catastro', referent_schema='configuracion', ondelete='SET NULL')
    op.create_foreign_key(None, 'referencias_ciudadanos', 'usuarios', ['creado_por_id'], ['id'], source_schema='catastro', referent_schema='configuracion', ondelete='SET NULL')
    op.drop_constraint(op.f('rutas_actualizado_por_id_fkey'), 'rutas', schema='catastro', type_='foreignkey')
    op.drop_constraint(op.f('rutas_creado_por_id_fkey'), 'rutas', schema='catastro', type_='foreignkey')
    op.create_foreign_key(None, 'rutas', 'usuarios', ['creado_por_id'], ['id'], source_schema='catastro', referent_schema='configuracion', ondelete='SET NULL')
    op.create_foreign_key(None, 'rutas', 'usuarios', ['actualizado_por_id'], ['id'], source_schema='catastro', referent_schema='configuracion', ondelete='SET NULL')
    op.drop_constraint(op.f('sectores_creado_por_id_fkey'), 'sectores', schema='catastro', type_='foreignkey')
    op.drop_constraint(op.f('sectores_actualizado_por_id_fkey'), 'sectores', schema='catastro', type_='foreignkey')
    op.create_foreign_key(None, 'sectores', 'usuarios', ['actualizado_por_id'], ['id'], source_schema='catastro', referent_schema='configuracion', ondelete='SET NULL')
    op.create_foreign_key(None, 'sectores', 'usuarios', ['creado_por_id'], ['id'], source_schema='catastro', referent_schema='configuracion', ondelete='SET NULL')
    op.drop_constraint(op.f('acometidas_actualizado_por_id_fkey'), 'acometidas', schema='comercial', type_='foreignkey')
    op.drop_constraint(op.f('acometidas_creado_por_id_fkey'), 'acometidas', schema='comercial', type_='foreignkey')
    op.create_foreign_key(None, 'acometidas', 'usuarios', ['creado_por_id'], ['id'], source_schema='comercial', referent_schema='configuracion', ondelete='SET NULL')
    op.create_foreign_key(None, 'acometidas', 'usuarios', ['actualizado_por_id'], ['id'], source_schema='comercial', referent_schema='configuracion', ondelete='SET NULL')
    op.drop_constraint(op.f('cuentas_creado_por_id_fkey'), 'cuentas', schema='comercial', type_='foreignkey')
    op.drop_constraint(op.f('cuentas_actualizado_por_id_fkey'), 'cuentas', schema='comercial', type_='foreignkey')
    op.create_foreign_key(None, 'cuentas', 'usuarios', ['creado_por_id'], ['id'], source_schema='comercial', referent_schema='configuracion', ondelete='SET NULL')
    op.create_foreign_key(None, 'cuentas', 'usuarios', ['actualizado_por_id'], ['id'], source_schema='comercial', referent_schema='configuracion', ondelete='SET NULL')
    op.drop_constraint(op.f('historial_medidor_cuenta_creado_por_id_fkey'), 'historial_medidor_cuenta', schema='comercial', type_='foreignkey')
    op.drop_constraint(op.f('historial_medidor_cuenta_actualizado_por_id_fkey'), 'historial_medidor_cuenta', schema='comercial', type_='foreignkey')
    op.create_foreign_key(None, 'historial_medidor_cuenta', 'usuarios', ['actualizado_por_id'], ['id'], source_schema='comercial', referent_schema='configuracion', ondelete='SET NULL')
    op.create_foreign_key(None, 'historial_medidor_cuenta', 'usuarios', ['creado_por_id'], ['id'], source_schema='comercial', referent_schema='configuracion', ondelete='SET NULL')
    op.drop_constraint(op.f('historial_tarifa_cuenta_creado_por_id_fkey'), 'historial_tarifa_cuenta', schema='comercial', type_='foreignkey')
    op.drop_constraint(op.f('historial_tarifa_cuenta_actualizado_por_id_fkey'), 'historial_tarifa_cuenta', schema='comercial', type_='foreignkey')
    op.create_foreign_key(None, 'historial_tarifa_cuenta', 'usuarios', ['actualizado_por_id'], ['id'], source_schema='comercial', referent_schema='configuracion', ondelete='SET NULL')
    op.create_foreign_key(None, 'historial_tarifa_cuenta', 'usuarios', ['creado_por_id'], ['id'], source_schema='comercial', referent_schema='configuracion', ondelete='SET NULL')
    op.drop_constraint(op.f('medidores_creado_por_id_fkey'), 'medidores', schema='comercial', type_='foreignkey')
    op.drop_constraint(op.f('medidores_actualizado_por_id_fkey'), 'medidores', schema='comercial', type_='foreignkey')
    op.create_foreign_key(None, 'medidores', 'usuarios', ['creado_por_id'], ['id'], source_schema='comercial', referent_schema='configuracion', ondelete='SET NULL')
    op.create_foreign_key(None, 'medidores', 'usuarios', ['actualizado_por_id'], ['id'], source_schema='comercial', referent_schema='configuracion', ondelete='SET NULL')
    op.drop_constraint(op.f('predios_actualizado_por_id_fkey'), 'predios', schema='comercial', type_='foreignkey')
    op.drop_constraint(op.f('predios_creado_por_id_fkey'), 'predios', schema='comercial', type_='foreignkey')
    op.create_foreign_key(None, 'predios', 'usuarios', ['creado_por_id'], ['id'], source_schema='comercial', referent_schema='configuracion', ondelete='SET NULL')
    op.create_foreign_key(None, 'predios', 'usuarios', ['actualizado_por_id'], ['id'], source_schema='comercial', referent_schema='configuracion', ondelete='SET NULL')
    op.drop_constraint(op.f('documento_generado_actualizado_por_id_fkey'), 'documento_generado', schema='contratacion', type_='foreignkey')
    op.drop_constraint(op.f('documento_generado_creado_por_id_fkey'), 'documento_generado', schema='contratacion', type_='foreignkey')
    op.create_foreign_key(None, 'documento_generado', 'usuarios', ['creado_por_id'], ['id'], source_schema='contratacion', referent_schema='configuracion', ondelete='SET NULL')
    op.create_foreign_key(None, 'documento_generado', 'usuarios', ['actualizado_por_id'], ['id'], source_schema='contratacion', referent_schema='configuracion', ondelete='SET NULL')
    op.drop_constraint(op.f('item_pac_actualizado_por_id_fkey'), 'item_pac', schema='contratacion', type_='foreignkey')
    op.drop_constraint(op.f('item_pac_creado_por_id_fkey'), 'item_pac', schema='contratacion', type_='foreignkey')
    op.create_foreign_key(None, 'item_pac', 'usuarios', ['creado_por_id'], ['id'], source_schema='contratacion', referent_schema='configuracion', ondelete='SET NULL')
    op.create_foreign_key(None, 'item_pac', 'usuarios', ['actualizado_por_id'], ['id'], source_schema='contratacion', referent_schema='configuracion', ondelete='SET NULL')
    op.drop_constraint(op.f('pac_anual_actualizado_por_id_fkey'), 'pac_anual', schema='contratacion', type_='foreignkey')
    op.drop_constraint(op.f('pac_anual_creado_por_id_fkey'), 'pac_anual', schema='contratacion', type_='foreignkey')
    op.create_foreign_key(None, 'pac_anual', 'usuarios', ['actualizado_por_id'], ['id'], source_schema='contratacion', referent_schema='configuracion', ondelete='SET NULL')
    op.create_foreign_key(None, 'pac_anual', 'usuarios', ['creado_por_id'], ['id'], source_schema='contratacion', referent_schema='configuracion', ondelete='SET NULL')
    op.drop_constraint(op.f('plantilla_documento_creado_por_id_fkey'), 'plantilla_documento', schema='contratacion', type_='foreignkey')
    op.drop_constraint(op.f('plantilla_documento_actualizado_por_id_fkey'), 'plantilla_documento', schema='contratacion', type_='foreignkey')
    op.create_foreign_key(None, 'plantilla_documento', 'usuarios', ['actualizado_por_id'], ['id'], source_schema='contratacion', referent_schema='configuracion', ondelete='SET NULL')
    op.create_foreign_key(None, 'plantilla_documento', 'usuarios', ['creado_por_id'], ['id'], source_schema='contratacion', referent_schema='configuracion', ondelete='SET NULL')
    op.drop_constraint(op.f('proceso_contratacion_creado_por_id_fkey'), 'proceso_contratacion', schema='contratacion', type_='foreignkey')
    op.drop_constraint(op.f('proceso_contratacion_usuario_id_fkey'), 'proceso_contratacion', schema='contratacion', type_='foreignkey')
    op.drop_constraint(op.f('proceso_contratacion_actualizado_por_id_fkey'), 'proceso_contratacion', schema='contratacion', type_='foreignkey')
    op.create_foreign_key(None, 'proceso_contratacion', 'usuarios', ['usuario_id'], ['id'], source_schema='contratacion', referent_schema='configuracion', ondelete='RESTRICT')
    op.create_foreign_key(None, 'proceso_contratacion', 'usuarios', ['actualizado_por_id'], ['id'], source_schema='contratacion', referent_schema='configuracion', ondelete='SET NULL')
    op.create_foreign_key(None, 'proceso_contratacion', 'usuarios', ['creado_por_id'], ['id'], source_schema='contratacion', referent_schema='configuracion', ondelete='SET NULL')
    op.drop_constraint(op.f('tipo_proceso_actualizado_por_id_fkey'), 'tipo_proceso', schema='contratacion', type_='foreignkey')
    op.drop_constraint(op.f('tipo_proceso_creado_por_id_fkey'), 'tipo_proceso', schema='contratacion', type_='foreignkey')
    op.create_foreign_key(None, 'tipo_proceso', 'usuarios', ['creado_por_id'], ['id'], source_schema='contratacion', referent_schema='configuracion', ondelete='SET NULL')
    op.create_foreign_key(None, 'tipo_proceso', 'usuarios', ['actualizado_por_id'], ['id'], source_schema='contratacion', referent_schema='configuracion', ondelete='SET NULL')
    op.drop_constraint(op.f('audit_logs_usuario_id_fkey'), 'audit_logs', schema='core', type_='foreignkey')
    op.create_foreign_key(None, 'audit_logs', 'usuarios', ['usuario_id'], ['id'], source_schema='core', referent_schema='configuracion', ondelete='SET NULL')
    op.drop_constraint(op.f('parametros_sistema_actualizado_por_id_fkey'), 'parametros_sistema', schema='core', type_='foreignkey')
    op.drop_constraint(op.f('parametros_sistema_creado_por_id_fkey'), 'parametros_sistema', schema='core', type_='foreignkey')
    op.create_foreign_key(None, 'parametros_sistema', 'usuarios', ['actualizado_por_id'], ['id'], source_schema='core', referent_schema='configuracion', ondelete='SET NULL')
    op.create_foreign_key(None, 'parametros_sistema', 'usuarios', ['creado_por_id'], ['id'], source_schema='core', referent_schema='configuracion', ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'parametros_sistema', schema='core', type_='foreignkey')
    op.drop_constraint(None, 'parametros_sistema', schema='core', type_='foreignkey')
    op.create_foreign_key(op.f('parametros_sistema_creado_por_id_fkey'), 'parametros_sistema', 'users', ['creado_por_id'], ['id'], source_schema='core', referent_schema='administracion', ondelete='SET NULL')
    op.create_foreign_key(op.f('parametros_sistema_actualizado_por_id_fkey'), 'parametros_sistema', 'users', ['actualizado_por_id'], ['id'], source_schema='core', referent_schema='administracion', ondelete='SET NULL')
    op.drop_constraint(None, 'audit_logs', schema='core', type_='foreignkey')
    op.create_foreign_key(op.f('audit_logs_usuario_id_fkey'), 'audit_logs', 'users', ['usuario_id'], ['id'], source_schema='core', referent_schema='administracion', ondelete='SET NULL')
    op.drop_constraint(None, 'tipo_proceso', schema='contratacion', type_='foreignkey')
    op.drop_constraint(None, 'tipo_proceso', schema='contratacion', type_='foreignkey')
    op.create_foreign_key(op.f('tipo_proceso_creado_por_id_fkey'), 'tipo_proceso', 'users', ['creado_por_id'], ['id'], source_schema='contratacion', referent_schema='administracion', ondelete='SET NULL')
    op.create_foreign_key(op.f('tipo_proceso_actualizado_por_id_fkey'), 'tipo_proceso', 'users', ['actualizado_por_id'], ['id'], source_schema='contratacion', referent_schema='administracion', ondelete='SET NULL')
    op.drop_constraint(None, 'proceso_contratacion', schema='contratacion', type_='foreignkey')
    op.drop_constraint(None, 'proceso_contratacion', schema='contratacion', type_='foreignkey')
    op.drop_constraint(None, 'proceso_contratacion', schema='contratacion', type_='foreignkey')
    op.create_foreign_key(op.f('proceso_contratacion_actualizado_por_id_fkey'), 'proceso_contratacion', 'users', ['actualizado_por_id'], ['id'], source_schema='contratacion', referent_schema='administracion', ondelete='SET NULL')
    op.create_foreign_key(op.f('proceso_contratacion_usuario_id_fkey'), 'proceso_contratacion', 'users', ['usuario_id'], ['id'], source_schema='contratacion', referent_schema='administracion', ondelete='RESTRICT')
    op.create_foreign_key(op.f('proceso_contratacion_creado_por_id_fkey'), 'proceso_contratacion', 'users', ['creado_por_id'], ['id'], source_schema='contratacion', referent_schema='administracion', ondelete='SET NULL')
    op.drop_constraint(None, 'plantilla_documento', schema='contratacion', type_='foreignkey')
    op.drop_constraint(None, 'plantilla_documento', schema='contratacion', type_='foreignkey')
    op.create_foreign_key(op.f('plantilla_documento_actualizado_por_id_fkey'), 'plantilla_documento', 'users', ['actualizado_por_id'], ['id'], source_schema='contratacion', referent_schema='administracion', ondelete='SET NULL')
    op.create_foreign_key(op.f('plantilla_documento_creado_por_id_fkey'), 'plantilla_documento', 'users', ['creado_por_id'], ['id'], source_schema='contratacion', referent_schema='administracion', ondelete='SET NULL')
    op.drop_constraint(None, 'pac_anual', schema='contratacion', type_='foreignkey')
    op.drop_constraint(None, 'pac_anual', schema='contratacion', type_='foreignkey')
    op.create_foreign_key(op.f('pac_anual_creado_por_id_fkey'), 'pac_anual', 'users', ['creado_por_id'], ['id'], source_schema='contratacion', referent_schema='administracion', ondelete='SET NULL')
    op.create_foreign_key(op.f('pac_anual_actualizado_por_id_fkey'), 'pac_anual', 'users', ['actualizado_por_id'], ['id'], source_schema='contratacion', referent_schema='administracion', ondelete='SET NULL')
    op.drop_constraint(None, 'item_pac', schema='contratacion', type_='foreignkey')
    op.drop_constraint(None, 'item_pac', schema='contratacion', type_='foreignkey')
    op.create_foreign_key(op.f('item_pac_creado_por_id_fkey'), 'item_pac', 'users', ['creado_por_id'], ['id'], source_schema='contratacion', referent_schema='administracion', ondelete='SET NULL')
    op.create_foreign_key(op.f('item_pac_actualizado_por_id_fkey'), 'item_pac', 'users', ['actualizado_por_id'], ['id'], source_schema='contratacion', referent_schema='administracion', ondelete='SET NULL')
    op.drop_constraint(None, 'documento_generado', schema='contratacion', type_='foreignkey')
    op.drop_constraint(None, 'documento_generado', schema='contratacion', type_='foreignkey')
    op.create_foreign_key(op.f('documento_generado_creado_por_id_fkey'), 'documento_generado', 'users', ['creado_por_id'], ['id'], source_schema='contratacion', referent_schema='administracion', ondelete='SET NULL')
    op.create_foreign_key(op.f('documento_generado_actualizado_por_id_fkey'), 'documento_generado', 'users', ['actualizado_por_id'], ['id'], source_schema='contratacion', referent_schema='administracion', ondelete='SET NULL')
    op.drop_constraint(None, 'predios', schema='comercial', type_='foreignkey')
    op.drop_constraint(None, 'predios', schema='comercial', type_='foreignkey')
    op.create_foreign_key(op.f('predios_creado_por_id_fkey'), 'predios', 'users', ['creado_por_id'], ['id'], source_schema='comercial', referent_schema='administracion', ondelete='SET NULL')
    op.create_foreign_key(op.f('predios_actualizado_por_id_fkey'), 'predios', 'users', ['actualizado_por_id'], ['id'], source_schema='comercial', referent_schema='administracion', ondelete='SET NULL')
    op.drop_constraint(None, 'medidores', schema='comercial', type_='foreignkey')
    op.drop_constraint(None, 'medidores', schema='comercial', type_='foreignkey')
    op.create_foreign_key(op.f('medidores_actualizado_por_id_fkey'), 'medidores', 'users', ['actualizado_por_id'], ['id'], source_schema='comercial', referent_schema='administracion', ondelete='SET NULL')
    op.create_foreign_key(op.f('medidores_creado_por_id_fkey'), 'medidores', 'users', ['creado_por_id'], ['id'], source_schema='comercial', referent_schema='administracion', ondelete='SET NULL')
    op.drop_constraint(None, 'historial_tarifa_cuenta', schema='comercial', type_='foreignkey')
    op.drop_constraint(None, 'historial_tarifa_cuenta', schema='comercial', type_='foreignkey')
    op.create_foreign_key(op.f('historial_tarifa_cuenta_actualizado_por_id_fkey'), 'historial_tarifa_cuenta', 'users', ['actualizado_por_id'], ['id'], source_schema='comercial', referent_schema='administracion', ondelete='SET NULL')
    op.create_foreign_key(op.f('historial_tarifa_cuenta_creado_por_id_fkey'), 'historial_tarifa_cuenta', 'users', ['creado_por_id'], ['id'], source_schema='comercial', referent_schema='administracion', ondelete='SET NULL')
    op.drop_constraint(None, 'historial_medidor_cuenta', schema='comercial', type_='foreignkey')
    op.drop_constraint(None, 'historial_medidor_cuenta', schema='comercial', type_='foreignkey')
    op.create_foreign_key(op.f('historial_medidor_cuenta_actualizado_por_id_fkey'), 'historial_medidor_cuenta', 'users', ['actualizado_por_id'], ['id'], source_schema='comercial', referent_schema='administracion', ondelete='SET NULL')
    op.create_foreign_key(op.f('historial_medidor_cuenta_creado_por_id_fkey'), 'historial_medidor_cuenta', 'users', ['creado_por_id'], ['id'], source_schema='comercial', referent_schema='administracion', ondelete='SET NULL')
    op.drop_constraint(None, 'cuentas', schema='comercial', type_='foreignkey')
    op.drop_constraint(None, 'cuentas', schema='comercial', type_='foreignkey')
    op.create_foreign_key(op.f('cuentas_actualizado_por_id_fkey'), 'cuentas', 'users', ['actualizado_por_id'], ['id'], source_schema='comercial', referent_schema='administracion', ondelete='SET NULL')
    op.create_foreign_key(op.f('cuentas_creado_por_id_fkey'), 'cuentas', 'users', ['creado_por_id'], ['id'], source_schema='comercial', referent_schema='administracion', ondelete='SET NULL')
    op.drop_constraint(None, 'acometidas', schema='comercial', type_='foreignkey')
    op.drop_constraint(None, 'acometidas', schema='comercial', type_='foreignkey')
    op.create_foreign_key(op.f('acometidas_creado_por_id_fkey'), 'acometidas', 'users', ['creado_por_id'], ['id'], source_schema='comercial', referent_schema='administracion', ondelete='SET NULL')
    op.create_foreign_key(op.f('acometidas_actualizado_por_id_fkey'), 'acometidas', 'users', ['actualizado_por_id'], ['id'], source_schema='comercial', referent_schema='administracion', ondelete='SET NULL')
    op.drop_constraint(None, 'sectores', schema='catastro', type_='foreignkey')
    op.drop_constraint(None, 'sectores', schema='catastro', type_='foreignkey')
    op.create_foreign_key(op.f('sectores_actualizado_por_id_fkey'), 'sectores', 'users', ['actualizado_por_id'], ['id'], source_schema='catastro', referent_schema='administracion', ondelete='SET NULL')
    op.create_foreign_key(op.f('sectores_creado_por_id_fkey'), 'sectores', 'users', ['creado_por_id'], ['id'], source_schema='catastro', referent_schema='administracion', ondelete='SET NULL')
    op.drop_constraint(None, 'rutas', schema='catastro', type_='foreignkey')
    op.drop_constraint(None, 'rutas', schema='catastro', type_='foreignkey')
    op.create_foreign_key(op.f('rutas_creado_por_id_fkey'), 'rutas', 'users', ['creado_por_id'], ['id'], source_schema='catastro', referent_schema='administracion', ondelete='SET NULL')
    op.create_foreign_key(op.f('rutas_actualizado_por_id_fkey'), 'rutas', 'users', ['actualizado_por_id'], ['id'], source_schema='catastro', referent_schema='administracion', ondelete='SET NULL')
    op.drop_constraint(None, 'referencias_ciudadanos', schema='catastro', type_='foreignkey')
    op.drop_constraint(None, 'referencias_ciudadanos', schema='catastro', type_='foreignkey')
    op.create_foreign_key(op.f('referencias_ciudadanos_creado_por_id_fkey'), 'referencias_ciudadanos', 'users', ['creado_por_id'], ['id'], source_schema='catastro', referent_schema='administracion', ondelete='SET NULL')
    op.create_foreign_key(op.f('referencias_ciudadanos_actualizado_por_id_fkey'), 'referencias_ciudadanos', 'users', ['actualizado_por_id'], ['id'], source_schema='catastro', referent_schema='administracion', ondelete='SET NULL')
    op.drop_constraint(None, 'redes', schema='catastro', type_='foreignkey')
    op.drop_constraint(None, 'redes', schema='catastro', type_='foreignkey')
    op.create_foreign_key(op.f('redes_actualizado_por_id_fkey'), 'redes', 'users', ['actualizado_por_id'], ['id'], source_schema='catastro', referent_schema='administracion', ondelete='SET NULL')
    op.create_foreign_key(op.f('redes_creado_por_id_fkey'), 'redes', 'users', ['creado_por_id'], ['id'], source_schema='catastro', referent_schema='administracion', ondelete='SET NULL')
    op.drop_constraint(None, 'ciudadanos', schema='catastro', type_='foreignkey')
    op.drop_constraint(None, 'ciudadanos', schema='catastro', type_='foreignkey')
    op.create_foreign_key(op.f('ciudadanos_actualizado_por_id_fkey'), 'ciudadanos', 'users', ['actualizado_por_id'], ['id'], source_schema='catastro', referent_schema='administracion', ondelete='SET NULL')
    op.create_foreign_key(op.f('ciudadanos_creado_por_id_fkey'), 'ciudadanos', 'users', ['creado_por_id'], ['id'], source_schema='catastro', referent_schema='administracion', ondelete='SET NULL')
    op.drop_constraint(None, 'calles', schema='catastro', type_='foreignkey')
    op.drop_constraint(None, 'calles', schema='catastro', type_='foreignkey')
    op.create_foreign_key(op.f('calles_actualizado_por_id_fkey'), 'calles', 'users', ['actualizado_por_id'], ['id'], source_schema='catastro', referent_schema='administracion', ondelete='SET NULL')
    op.create_foreign_key(op.f('calles_creado_por_id_fkey'), 'calles', 'users', ['creado_por_id'], ['id'], source_schema='catastro', referent_schema='administracion', ondelete='SET NULL')
    op.drop_constraint(None, 'barrios', schema='catastro', type_='foreignkey')
    op.drop_constraint(None, 'barrios', schema='catastro', type_='foreignkey')
    op.create_foreign_key(op.f('barrios_actualizado_por_id_fkey'), 'barrios', 'users', ['actualizado_por_id'], ['id'], source_schema='catastro', referent_schema='administracion', ondelete='SET NULL')
    op.create_foreign_key(op.f('barrios_creado_por_id_fkey'), 'barrios', 'users', ['creado_por_id'], ['id'], source_schema='catastro', referent_schema='administracion', ondelete='SET NULL')
    op.drop_constraint(None, 'personal', schema='administracion', type_='foreignkey')
    op.create_foreign_key(op.f('personal_usuario_id_fkey'), 'personal', 'users', ['usuario_id'], ['id'], source_schema='administracion', referent_schema='administracion', ondelete='SET NULL')
    op.drop_index(op.f('ix_configuracion_usuarios_id'), table_name='usuarios', schema='configuracion')
    op.drop_index(op.f('ix_configuracion_usuarios_correo'), table_name='usuarios', schema='configuracion')
    op.drop_index(op.f('ix_configuracion_usuarios_cedula'), table_name='usuarios', schema='configuracion')
    op.drop_table('usuarios', schema='configuracion')
    op.drop_table('rol_permiso', schema='configuracion')
    op.drop_index(op.f('ix_configuracion_roles_nombre_rol'), table_name='roles', schema='configuracion')
    op.drop_index(op.f('ix_configuracion_roles_id'), table_name='roles', schema='configuracion')
    op.drop_table('roles', schema='configuracion')
    op.drop_index(op.f('ix_configuracion_permisos_nombre_permiso'), table_name='permisos', schema='configuracion')
    op.drop_index(op.f('ix_configuracion_permisos_id'), table_name='permisos', schema='configuracion')
    op.drop_table('permisos', schema='configuracion')
    # ### end Alembic commands ###
