"""Add informatica IPAM

Revision ID: 1d7a08053a2c
Revises: d7c5d8e774cb
Create Date: 2026-03-09 23:56:38.130312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d7a08053a2c'
down_revision: Union[str, Sequence[str], None] = 'd7c5d8e774cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('segmento_red',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('red_cidr', sa.String(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='informatica'
    )
    op.create_index(op.f('ix_informatica_segmento_red_id'), 'segmento_red', ['id'], unique=False, schema='informatica')
    op.create_table('direccion_ip_asignada',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('segmento_id', sa.String(), nullable=False),
    sa.Column('direccion_ip', sa.String(), nullable=False),
    sa.Column('mac_address', sa.String(), nullable=True),
    sa.Column('nombre_equipo', sa.String(), nullable=True),
    sa.Column('dominio', sa.String(), nullable=True),
    sa.Column('ubicacion_geografica', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['segmento_id'], ['informatica.segmento_red.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('direccion_ip'),
    schema='informatica'
    )
    op.create_index(op.f('ix_informatica_direccion_ip_asignada_id'), 'direccion_ip_asignada', ['id'], unique=False, schema='informatica')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_informatica_direccion_ip_asignada_id'), table_name='direccion_ip_asignada', schema='informatica')
    op.drop_table('direccion_ip_asignada', schema='informatica')
    op.drop_index(op.f('ix_informatica_segmento_red_id'), table_name='segmento_red', schema='informatica')
    op.drop_table('segmento_red', schema='informatica')
    # ### end Alembic commands ###
