"""Add foto_fachada a Predio

Revision ID: 2798487064aa
Revises: 8a8394d0a2f8
Create Date: 2026-03-03 04:06:06.732471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2798487064aa'
down_revision: Union[str, Sequence[str], None] = '8a8394d0a2f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('predios', sa.Column('foto_fachada', sa.String(length=255), nullable=True))
    op.add_column('predios', sa.Column('croquis', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('predios', 'croquis')
    op.drop_column('predios', 'foto_fachada')
    # ### end Alembic commands ###
