"""Add bodega module and relations

Revision ID: 29f0ea2413ff
Revises: 3f0e41ee9a01
Create Date: 2026-03-10 00:35:23.180566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29f0ea2413ff'
down_revision: Union[str, Sequence[str], None] = '3f0e41ee9a01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA IF NOT EXISTS bodega;")
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre'),
    schema='bodega'
    )
    op.create_index(op.f('ix_bodega_categorias_id'), 'categorias', ['id'], unique=False, schema='bodega')
    op.create_table('activos_fijos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_inventario', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('marca', sa.String(length=100), nullable=True),
    sa.Column('modelo', sa.String(length=100), nullable=True),
    sa.Column('numero_serie', sa.String(length=100), nullable=True),
    sa.Column('costo_inicial', sa.Float(), nullable=True),
    sa.Column('valor_depreciado', sa.Float(), nullable=True),
    sa.Column('fecha_compra', sa.Date(), nullable=True),
    sa.Column('factura_referencia', sa.String(length=100), nullable=True),
    sa.Column('estado_fisico', sa.Enum('BUENO', 'REGULAR', 'MALO', 'DE_BAJA', name='estado_fisico'), nullable=True),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['bodega.categorias.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='bodega'
    )
    op.create_index(op.f('ix_bodega_activos_fijos_codigo_inventario'), 'activos_fijos', ['codigo_inventario'], unique=True, schema='bodega')
    op.create_index(op.f('ix_bodega_activos_fijos_id'), 'activos_fijos', ['id'], unique=False, schema='bodega')
    op.add_column('direccion_ip_asignada', sa.Column('activo_id', sa.Integer(), nullable=True), schema='informatica')
    op.create_foreign_key(None, 'direccion_ip_asignada', 'activos_fijos', ['activo_id'], ['id'], source_schema='informatica', referent_schema='bodega')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'direccion_ip_asignada', schema='informatica', type_='foreignkey')
    op.drop_column('direccion_ip_asignada', 'activo_id', schema='informatica')
    op.drop_index(op.f('ix_bodega_activos_fijos_id'), table_name='activos_fijos', schema='bodega')
    op.drop_index(op.f('ix_bodega_activos_fijos_codigo_inventario'), table_name='activos_fijos', schema='bodega')
    op.drop_table('activos_fijos', schema='bodega')
    op.drop_index(op.f('ix_bodega_categorias_id'), table_name='categorias', schema='bodega')
    op.drop_table('categorias', schema='bodega')
    op.execute("DROP SCHEMA IF EXISTS bodega CASCADE;")
    # ### end Alembic commands ###
