"""Fix relations and schemas

Revision ID: 3748c6e1f016
Revises: 9506ab7a1839
Create Date: 2026-03-09 21:40:47.616991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3748c6e1f016'
down_revision: Union[str, Sequence[str], None] = '9506ab7a1839'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('direcciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('es_activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre'),
    schema='administracion'
    )
    op.create_index(op.f('ix_administracion_direcciones_id'), 'direcciones', ['id'], unique=False, schema='administracion')
    op.create_table('puestos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('denominacion', sa.String(length=150), nullable=False),
    sa.Column('escala_ocupacional', sa.String(length=100), nullable=True),
    sa.Column('remuneracion_mensual', sa.Float(), nullable=False),
    sa.Column('partida_presupuestaria', sa.String(length=100), nullable=False),
    sa.Column('es_activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='administracion'
    )
    op.create_index(op.f('ix_administracion_puestos_id'), 'puestos', ['id'], unique=False, schema='administracion')
    op.create_table('unidades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('direccion_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('es_activo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['direccion_id'], ['administracion.direcciones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='administracion'
    )
    op.create_index(op.f('ix_administracion_unidades_id'), 'unidades', ['id'], unique=False, schema='administracion')
    op.create_table('personal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unidad_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('puesto_id', sa.Integer(), nullable=True),
    sa.Column('cedula', sa.String(length=20), nullable=False),
    sa.Column('nombres', sa.String(length=100), nullable=False),
    sa.Column('apellidos', sa.String(length=100), nullable=False),
    sa.Column('cargo', sa.String(length=150), nullable=False),
    sa.Column('regimen_legal', sa.Enum('LOEP', 'CODIGO_TRABAJO', name='tipo_regimen_legal'), nullable=False),
    sa.Column('tipo_contrato', sa.Enum('NOMBRAMIENTO', 'INDEFINIDO', 'CONTRATADO_LOEP', 'CONTRATADO_CT', 'REQUERIDO_PROYECTO', name='tipo_contrato'), nullable=False),
    sa.Column('codigo_certificacion_sercop', sa.String(length=100), nullable=True),
    sa.Column('foto_perfil', sa.String(), nullable=True),
    sa.Column('direccion_domicilio', sa.String(length=255), nullable=True),
    sa.Column('telefono_celular', sa.String(length=20), nullable=True),
    sa.Column('correo_personal', sa.String(length=100), nullable=True),
    sa.Column('archivo_firma_electronica', sa.String(), nullable=True),
    sa.Column('es_activo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['puesto_id'], ['administracion.puestos.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['unidad_id'], ['administracion.unidades.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['usuario_id'], ['administracion.users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id'),
    schema='administracion'
    )
    op.create_index(op.f('ix_administracion_personal_cedula'), 'personal', ['cedula'], unique=True, schema='administracion')
    op.create_index(op.f('ix_administracion_personal_id'), 'personal', ['id'], unique=False, schema='administracion')
    op.create_table('pac_anual',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('version_reforma', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('es_activo', sa.Boolean(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('creado_por_id', sa.Integer(), nullable=True),
    sa.Column('actualizado_por_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['actualizado_por_id'], ['administracion.users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['creado_por_id'], ['administracion.users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='contratacion'
    )
    op.create_index(op.f('ix_contratacion_pac_anual_id'), 'pac_anual', ['id'], unique=False, schema='contratacion')
    op.create_table('titulos_profesionales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('personal_id', sa.Integer(), nullable=False),
    sa.Column('nivel', sa.Enum('TECNICO', 'TECNOLOGICO', 'TERCER_NIVEL', 'CUARTO_NIVEL', 'PHD', name='nivel_educacion'), nullable=False),
    sa.Column('nombre_titulo', sa.String(length=200), nullable=False),
    sa.Column('institucion', sa.String(length=200), nullable=False),
    sa.Column('registro_senescyt', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['personal_id'], ['administracion.personal.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='administracion'
    )
    op.create_index(op.f('ix_administracion_titulos_profesionales_id'), 'titulos_profesionales', ['id'], unique=False, schema='administracion')
    op.create_table('item_pac',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pac_anual_id', sa.Integer(), nullable=False),
    sa.Column('partida_presupuestaria', sa.String(length=100), nullable=False),
    sa.Column('cpc', sa.String(length=50), nullable=True),
    sa.Column('tipo_compra', sa.String(length=100), nullable=True),
    sa.Column('procedimiento', sa.String(length=100), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('cantidad', sa.Float(), nullable=False),
    sa.Column('costo_unitario', sa.Float(), nullable=False),
    sa.Column('valor_total', sa.Float(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('creado_por_id', sa.Integer(), nullable=True),
    sa.Column('actualizado_por_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['actualizado_por_id'], ['administracion.users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['creado_por_id'], ['administracion.users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pac_anual_id'], ['contratacion.pac_anual.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='contratacion'
    )
    op.create_index(op.f('ix_contratacion_item_pac_id'), 'item_pac', ['id'], unique=False, schema='contratacion')
    op.create_table('proceso_item_pac_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proceso_id', sa.Integer(), nullable=False),
    sa.Column('item_pac_id', sa.Integer(), nullable=False),
    sa.Column('monto_comprometido', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['item_pac_id'], ['contratacion.item_pac.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['proceso_id'], ['contratacion.proceso_contratacion.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='contratacion'
    )
    op.create_index(op.f('ix_contratacion_proceso_item_pac_link_id'), 'proceso_item_pac_link', ['id'], unique=False, schema='contratacion')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contratacion_proceso_item_pac_link_id'), table_name='proceso_item_pac_link', schema='contratacion')
    op.drop_table('proceso_item_pac_link', schema='contratacion')
    op.drop_index(op.f('ix_contratacion_item_pac_id'), table_name='item_pac', schema='contratacion')
    op.drop_table('item_pac', schema='contratacion')
    op.drop_index(op.f('ix_administracion_titulos_profesionales_id'), table_name='titulos_profesionales', schema='administracion')
    op.drop_table('titulos_profesionales', schema='administracion')
    op.drop_index(op.f('ix_contratacion_pac_anual_id'), table_name='pac_anual', schema='contratacion')
    op.drop_table('pac_anual', schema='contratacion')
    op.drop_index(op.f('ix_administracion_personal_id'), table_name='personal', schema='administracion')
    op.drop_index(op.f('ix_administracion_personal_cedula'), table_name='personal', schema='administracion')
    op.drop_table('personal', schema='administracion')
    op.drop_index(op.f('ix_administracion_unidades_id'), table_name='unidades', schema='administracion')
    op.drop_table('unidades', schema='administracion')
    op.drop_index(op.f('ix_administracion_puestos_id'), table_name='puestos', schema='administracion')
    op.drop_table('puestos', schema='administracion')
    op.drop_index(op.f('ix_administracion_direcciones_id'), table_name='direcciones', schema='administracion')
    op.drop_table('direcciones', schema='administracion')
    # ### end Alembic commands ###
