"""Update tipo_proceso fields for SERCOP tree

Revision ID: 3d152c45f2fb
Revises: c7ee85c09d3f
Create Date: 2026-03-08 03:34:32.598879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d152c45f2fb'
down_revision: Union[str, Sequence[str], None] = 'c7ee85c09d3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
