"""Creacion CRM Ciudadanos y Referencias

Revision ID: 3d5bf4738387
Revises: 3f5ffc512d02
Create Date: 2026-03-03 03:24:59.265245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3d5bf4738387'
down_revision: Union[str, Sequence[str], None] = '3f5ffc512d02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ciudadanos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_persona', sa.String(length=20), nullable=False),
    sa.Column('identificacion', sa.String(length=20), nullable=False),
    sa.Column('nombres', sa.String(length=100), nullable=True),
    sa.Column('apellidos', sa.String(length=100), nullable=True),
    sa.Column('razon_social', sa.String(length=200), nullable=True),
    sa.Column('correo_principal', sa.String(length=150), nullable=True),
    sa.Column('telefono_fijo', sa.String(length=20), nullable=True),
    sa.Column('celular', sa.String(length=20), nullable=True),
    sa.Column('preferencia_contacto', sa.String(length=50), nullable=True),
    sa.Column('redes_sociales', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('nacionalidad', sa.String(length=50), nullable=True),
    sa.Column('genero', sa.String(length=20), nullable=True),
    sa.Column('estado_civil', sa.String(length=50), nullable=True),
    sa.Column('tiene_discapacidad', sa.Boolean(), nullable=True),
    sa.Column('porcentaje_discapacidad', sa.Float(), nullable=True),
    sa.Column('aplica_tercera_edad', sa.Boolean(), nullable=True),
    sa.Column('tipo_empresa', sa.String(length=50), nullable=True),
    sa.Column('naturaleza_juridica', sa.String(length=50), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('creado_por_id', sa.Integer(), nullable=True),
    sa.Column('actualizado_por_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['actualizado_por_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['creado_por_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ciudadanos_id'), 'ciudadanos', ['id'], unique=False)
    op.create_index(op.f('ix_ciudadanos_identificacion'), 'ciudadanos', ['identificacion'], unique=True)
    op.create_table('referencias_ciudadanos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ciudadano_id', sa.Integer(), nullable=False),
    sa.Column('tipo_referencia', sa.String(length=50), nullable=False),
    sa.Column('nombres', sa.String(length=100), nullable=False),
    sa.Column('apellidos', sa.String(length=100), nullable=False),
    sa.Column('identificacion', sa.String(length=20), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('correo', sa.String(length=150), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('creado_por_id', sa.Integer(), nullable=True),
    sa.Column('actualizado_por_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['actualizado_por_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ciudadano_id'], ['ciudadanos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['creado_por_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_referencias_ciudadanos_id'), 'referencias_ciudadanos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_referencias_ciudadanos_id'), table_name='referencias_ciudadanos')
    op.drop_table('referencias_ciudadanos')
    op.drop_index(op.f('ix_ciudadanos_identificacion'), table_name='ciudadanos')
    op.drop_index(op.f('ix_ciudadanos_id'), table_name='ciudadanos')
    op.drop_table('ciudadanos')
    # ### end Alembic commands ###
