"""Add personal_id to DireccionIpAsignada

Revision ID: 3f0e41ee9a01
Revises: 1d7a08053a2c
Create Date: 2026-03-10 00:25:41.347157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f0e41ee9a01'
down_revision: Union[str, Sequence[str], None] = '1d7a08053a2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('direccion_ip_asignada', sa.Column('personal_id', sa.Integer(), nullable=True), schema='informatica')
    op.create_foreign_key(None, 'direccion_ip_asignada', 'personal', ['personal_id'], ['id'], source_schema='informatica', referent_schema='administracion')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'direccion_ip_asignada', schema='informatica', type_='foreignkey')
    op.drop_column('direccion_ip_asignada', 'personal_id', schema='informatica')
    # ### end Alembic commands ###
