"""Creacion tabla Parametros y modulo GIS

Revision ID: 3f5ffc512d02
Revises: 312645140c78
Create Date: 2026-03-03 02:59:38.024389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '3f5ffc512d02'
down_revision: Union[str, Sequence[str], None] = '312645140c78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tabla_afectada', sa.String(length=100), nullable=False),
    sa.Column('registro_id', sa.Integer(), nullable=False),
    sa.Column('accion', sa.String(length=50), nullable=False),
    sa.Column('valores_viejos', sa.Text(), nullable=True),
    sa.Column('valores_nuevos', sa.Text(), nullable=True),
    sa.Column('fecha_evento', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_registro_id'), 'audit_logs', ['registro_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_tabla_afectada'), 'audit_logs', ['tabla_afectada'], unique=False)
    op.create_table('barrios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('geometria', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('creado_por_id', sa.Integer(), nullable=True),
    sa.Column('actualizado_por_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['actualizado_por_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['creado_por_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
        # op.create_index(..., barrios)
    op.create_index(op.f('ix_barrios_id'), 'barrios', ['id'], unique=False)
    op.create_index(op.f('ix_barrios_nombre'), 'barrios', ['nombre'], unique=False)
    op.create_table('calles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('geometria', geoalchemy2.types.Geometry(geometry_type='MULTILINESTRING', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('creado_por_id', sa.Integer(), nullable=True),
    sa.Column('actualizado_por_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['actualizado_por_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['creado_por_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
        # op.create_index(..., calles)
    op.create_index(op.f('ix_calles_id'), 'calles', ['id'], unique=False)
    op.create_index(op.f('ix_calles_nombre'), 'calles', ['nombre'], unique=False)
    op.create_table('parametros_sistema',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clave', sa.String(length=100), nullable=False),
    sa.Column('valor', sa.String(length=255), nullable=False),
    sa.Column('tipo_dato', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('creado_por_id', sa.Integer(), nullable=True),
    sa.Column('actualizado_por_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['actualizado_por_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['creado_por_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parametros_sistema_clave'), 'parametros_sistema', ['clave'], unique=True)
    op.create_index(op.f('ix_parametros_sistema_id'), 'parametros_sistema', ['id'], unique=False)
    op.create_table('redes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('creado_por_id', sa.Integer(), nullable=True),
    sa.Column('actualizado_por_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['actualizado_por_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['creado_por_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_redes_codigo'), 'redes', ['codigo'], unique=True)
    op.create_index(op.f('ix_redes_id'), 'redes', ['id'], unique=False)
    op.create_table('sectores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('red_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('codigo_sector', sa.String(length=50), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('creado_por_id', sa.Integer(), nullable=True),
    sa.Column('actualizado_por_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['actualizado_por_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['creado_por_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['red_id'], ['redes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sectores_codigo_sector'), 'sectores', ['codigo_sector'], unique=True)
    op.create_index(op.f('ix_sectores_id'), 'sectores', ['id'], unique=False)
    op.create_table('rutas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sector_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('codigo_ruta', sa.String(length=50), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('creado_por_id', sa.Integer(), nullable=True),
    sa.Column('actualizado_por_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['actualizado_por_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['creado_por_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sector_id'], ['sectores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rutas_codigo_ruta'), 'rutas', ['codigo_ruta'], unique=True)
    op.create_index(op.f('ix_rutas_id'), 'rutas', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rutas_id'), table_name='rutas')
    op.drop_index(op.f('ix_rutas_codigo_ruta'), table_name='rutas')
    op.drop_table('rutas')
    op.drop_index(op.f('ix_sectores_id'), table_name='sectores')
    op.drop_index(op.f('ix_sectores_codigo_sector'), table_name='sectores')
    op.drop_table('sectores')
    op.drop_index(op.f('ix_redes_id'), table_name='redes')
    op.drop_index(op.f('ix_redes_codigo'), table_name='redes')
    op.drop_table('redes')
    op.drop_index(op.f('ix_parametros_sistema_id'), table_name='parametros_sistema')
    op.drop_index(op.f('ix_parametros_sistema_clave'), table_name='parametros_sistema')
    op.drop_table('parametros_sistema')
    op.drop_index(op.f('ix_calles_nombre'), table_name='calles')
    op.drop_index(op.f('ix_calles_id'), table_name='calles')
    op.drop_index('idx_calles_geometria', table_name='calles', postgresql_using='gist')
    op.drop_table('calles')
    op.drop_index(op.f('ix_barrios_nombre'), table_name='barrios')
    op.drop_index(op.f('ix_barrios_id'), table_name='barrios')
    op.drop_index('idx_barrios_geometria', table_name='barrios', postgresql_using='gist')
    op.drop_table('barrios')
    op.drop_index(op.f('ix_audit_logs_tabla_afectada'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_registro_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
