"""Fix plantilla model columns 3

Revision ID: 4de2d85123cf
Revises: 2b8edf0cf982
Create Date: 2026-03-08 03:53:01.076195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4de2d85123cf'
down_revision: Union[str, Sequence[str], None] = '2b8edf0cf982'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
