"""fix_is_activa_definitivo

Revision ID: 5cedf87db14a
Revises: 8d99c07e28d2
Create Date: 2026-03-08 04:11:44.872181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cedf87db14a'
down_revision: Union[str, Sequence[str], None] = '8d99c07e28d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
