"""Add is_active to ciudadano

Revision ID: 7615c88b61fa
Revises: 2798487064aa
Create Date: 2026-03-03 04:37:12.957876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7615c88b61fa'
down_revision: Union[str, Sequence[str], None] = '2798487064aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ciudadanos', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ciudadanos', 'is_active')
    # ### end Alembic commands ###
