"""Add foto_fachada a Predio

Revision ID: 8a8394d0a2f8
Revises: aa1f73fc182c
Create Date: 2026-03-03 04:05:56.318053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a8394d0a2f8'
down_revision: Union[str, Sequence[str], None] = 'aa1f73fc182c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
