"""Update tipo_proceso fields for SERCOP tree

Revision ID: 8cd6accc5621
Revises: 3d152c45f2fb
Create Date: 2026-03-08 03:35:07.810674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cd6accc5621'
down_revision: Union[str, Sequence[str], None] = '3d152c45f2fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plantilla_documento', sa.Column('categoria', sa.String(length=50), server_default='Bienes y Servicios', nullable=False), schema='contratacion')
    op.add_column('plantilla_documento', sa.Column('condicion_monto', sa.String(length=255), nullable=True), schema='contratacion')
    op.add_column('plantilla_documento', sa.Column('is_activo', sa.Boolean(), server_default='true', nullable=False), schema='contratacion')
    op.add_column('tipo_proceso', sa.Column('categoria', sa.String(length=50), server_default='Bienes y Servicios', nullable=False), schema='contratacion')
    op.add_column('tipo_proceso', sa.Column('condicion_monto', sa.String(length=255), nullable=True), schema='contratacion')
    op.add_column('tipo_proceso', sa.Column('is_activo', sa.Boolean(), server_default='true', nullable=False), schema='contratacion')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tipo_proceso', 'is_activo', schema='contratacion')
    op.drop_column('tipo_proceso', 'condicion_monto', schema='contratacion')
    op.drop_column('tipo_proceso', 'categoria', schema='contratacion')
    op.drop_column('plantilla_documento', 'is_activo', schema='contratacion')
    op.drop_column('plantilla_documento', 'condicion_monto', schema='contratacion')
    op.drop_column('plantilla_documento', 'categoria', schema='contratacion')
    # ### end Alembic commands ###
