"""Creacion modulo administrativo y PAC

Revision ID: 9506ab7a1839
Revises: e6ac70f05d87
Create Date: 2026-03-09 21:34:15.966439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9506ab7a1839'
down_revision: Union[str, Sequence[str], None] = 'e6ac70f05d87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
