"""Add tipo_proceso_id to ProcesoContratacion

Revision ID: 9d35b896c2cd
Revises: b80aa431f85d
Create Date: 2026-03-07 23:56:32.231049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d35b896c2cd'
down_revision: Union[str, Sequence[str], None] = 'b80aa431f85d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proceso_contratacion', sa.Column('tipo_proceso_id', sa.Integer(), nullable=True), schema='contratacion')
    op.create_foreign_key(None, 'proceso_contratacion', 'tipo_proceso', ['tipo_proceso_id'], ['id'], source_schema='contratacion', referent_schema='contratacion', ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'proceso_contratacion', schema='contratacion', type_='foreignkey')
    op.drop_column('proceso_contratacion', 'tipo_proceso_id', schema='contratacion')
    # ### end Alembic commands ###
