"""fix_administracion_audit_columns

Revision ID: a5dd8cea9dd3
Revises: c004
Create Date: 2026-04-04 02:27:00.239229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a5dd8cea9dd3'
down_revision: Union[str, Sequence[str], None] = 'c004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partidas_presupuestarias',
    sa.Column('id_partida', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.String(length=30), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('nivel', sa.Integer(), nullable=False),
    sa.Column('es_hoja', sa.Boolean(), nullable=True),
    sa.Column('id_partida_padre', sa.BigInteger(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_partida_padre'], ['presupuesto.partidas_presupuestarias.id_partida'], ),
    sa.PrimaryKeyConstraint('id_partida'),
    sa.UniqueConstraint('codigo', name='uq_partida_codigo'),
    schema='presupuesto'
    )
    op.create_index(op.f('ix_presupuesto_partidas_presupuestarias_codigo'), 'partidas_presupuestarias', ['codigo'], unique=False, schema='presupuesto')
    op.create_table('presupuestos_anuales',
    sa.Column('id_presupuesto', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('anio_fiscal', sa.Integer(), nullable=False),
    sa.Column('denominacion', sa.String(length=255), nullable=False),
    sa.Column('monto_inicial', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('monto_codificado', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('fecha_aprobacion', sa.Date(), nullable=True),
    sa.Column('resolucion_aprobacion', sa.String(length=100), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id_presupuesto'),
    sa.UniqueConstraint('anio_fiscal', 'estado', name='uq_presupuesto_anio_aprobado'),
    schema='presupuesto'
    )
    op.create_index(op.f('ix_presupuesto_presupuestos_anuales_anio_fiscal'), 'presupuestos_anuales', ['anio_fiscal'], unique=False, schema='presupuesto')
    op.create_table('area_organizacional',
    sa.Column('id_area', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('id_area_padre', sa.BigInteger(), nullable=True),
    sa.Column('tipo_area', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['id_area_padre'], ['rrhh.area_organizacional.id_area'], ),
    sa.PrimaryKeyConstraint('id_area'),
    schema='rrhh'
    )
    op.create_table('escala_salarial',
    sa.Column('id_escala', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('grado', sa.String(length=20), nullable=False),
    sa.Column('salario_base', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('regimen_laboral', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_escala'),
    schema='rrhh'
    )
    op.create_table('impuesto_renta_escala',
    sa.Column('id_escala', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('anio_vigencia', sa.Integer(), nullable=False),
    sa.Column('fraccion_basica', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('exceso_hasta', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('impuesto_fraccion_basica', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('porcentaje_fraccion_excedente', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id_escala'),
    schema='rrhh'
    )
    op.create_table('parametro_calculo',
    sa.Column('id_parametro', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('anio_vigencia', sa.Integer(), nullable=False),
    sa.Column('codigo_parametro', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=150), nullable=True),
    sa.Column('valor_numerico', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('valor_texto', sa.String(length=255), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id_parametro'),
    sa.UniqueConstraint('anio_vigencia', 'codigo_parametro', name='uq_parametro_anio_codigo_rrhh'),
    schema='rrhh'
    )
    op.create_table('rubro_nomina',
    sa.Column('id_rubro', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('codigo_rubro', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('naturaleza', sa.String(length=20), nullable=False),
    sa.Column('tipo_valor', sa.String(length=20), nullable=False),
    sa.Column('formula_calculo', sa.Text(), nullable=True),
    sa.Column('orden_ejecucion', sa.Integer(), nullable=False),
    sa.Column('es_imponible', sa.Boolean(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id_rubro'),
    sa.UniqueConstraint('codigo_rubro'),
    schema='rrhh'
    )
    op.create_table('asignaciones_presupuestarias',
    sa.Column('id_asignacion', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('id_presupuesto', sa.BigInteger(), nullable=False),
    sa.Column('id_partida', sa.BigInteger(), nullable=False),
    sa.Column('monto_inicial', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('monto_codificado', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('monto_comprometido', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('monto_devengado', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('monto_pagado', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_partida'], ['presupuesto.partidas_presupuestarias.id_partida'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_presupuesto'], ['presupuesto.presupuestos_anuales.id_presupuesto'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_asignacion'),
    sa.UniqueConstraint('id_presupuesto', 'id_partida', name='uq_asignacion_presupuesto_partida'),
    schema='presupuesto'
    )
    op.create_table('cargo',
    sa.Column('id_cargo', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nombre_cargo', sa.String(length=150), nullable=False),
    sa.Column('id_escala_salarial', sa.BigInteger(), nullable=True),
    sa.Column('partida_presupuestaria', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['id_escala_salarial'], ['rrhh.escala_salarial.id_escala'], ),
    sa.PrimaryKeyConstraint('id_cargo'),
    schema='rrhh'
    )
    op.create_table('tipos_documento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=10), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False, comment='FACTURA|NOTA_CREDITO|NOTA_DEBITO|LIQUIDACION|PROFORMA|CERTIFICADO_PRESUPUESTARIO'),
    sa.Column('secuencia_prefijo', sa.String(length=10), nullable=True, comment='Prefijo para numeración, ej: FAC-'),
    sa.Column('secuencia_siguiente', sa.Integer(), nullable=False),
    sa.Column('es_activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('creado_por_id', sa.Integer(), nullable=True),
    sa.Column('actualizado_por_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['actualizado_por_id'], ['configuracion.usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['creado_por_id'], ['configuracion.usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo', name='uq_tipos_documento_codigo'),
    schema='financiero'
    )
    op.create_index(op.f('ix_financiero_tipos_documento_id'), 'tipos_documento', ['id'], unique=False, schema='financiero')
    op.create_table('reformas_presupuestarias',
    sa.Column('id_reforma', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('id_asignacion', sa.BigInteger(), nullable=False),
    sa.Column('tipo_reforma', sa.String(length=30), nullable=False),
    sa.Column('monto', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('numero_resolucion', sa.String(length=100), nullable=False),
    sa.Column('fecha_resolucion', sa.Date(), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_asignacion'], ['presupuesto.asignaciones_presupuestarias.id_asignacion'], ),
    sa.PrimaryKeyConstraint('id_reforma'),
    schema='presupuesto'
    )
    op.create_table('empleado',
    sa.Column('id_empleado', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tipo_identificacion', sa.String(length=20), nullable=True),
    sa.Column('identificacion', sa.String(length=20), nullable=False),
    sa.Column('nombres', sa.String(length=100), nullable=False),
    sa.Column('apellidos', sa.String(length=100), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=False),
    sa.Column('genero', sa.String(length=20), nullable=True),
    sa.Column('porcentaje_discapacidad', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('aplica_iess', sa.Boolean(), nullable=True),
    sa.Column('acumula_fondos_reserva', sa.Boolean(), nullable=True),
    sa.Column('acumula_decimos', sa.Boolean(), nullable=True),
    sa.Column('regimen_legal', sa.String(length=50), nullable=True),
    sa.Column('tipo_contrato_actual', sa.String(length=50), nullable=True),
    sa.Column('codigo_sercop', sa.String(length=100), nullable=True),
    sa.Column('archivo_firma_electronica', sa.String(), nullable=True),
    sa.Column('telefono_celular', sa.String(length=20), nullable=True),
    sa.Column('correo_personal', sa.String(length=100), nullable=True),
    sa.Column('direccion_domicilio', sa.String(length=255), nullable=True),
    sa.Column('foto_perfil', sa.String(), nullable=True),
    sa.Column('usuario_id', sa.BigInteger(), nullable=True),
    sa.Column('estado_empleado', sa.String(length=50), nullable=True),
    sa.Column('eliminado_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('creado_por_id', sa.BigInteger(), nullable=True),
    sa.Column('actualizado_por_id', sa.BigInteger(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['actualizado_por_id'], ['configuracion.usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['creado_por_id'], ['configuracion.usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['usuario_id'], ['configuracion.usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id_empleado'),
    sa.UniqueConstraint('usuario_id'),
    schema='rrhh'
    )
    op.create_index(op.f('ix_rrhh_empleado_identificacion'), 'empleado', ['identificacion'], unique=True, schema='rrhh')
    op.create_table('entidades_bancarias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('sigla', sa.String(length=20), nullable=True),
    sa.Column('es_activa', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('creado_por_id', sa.Integer(), nullable=True),
    sa.Column('actualizado_por_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['actualizado_por_id'], ['configuracion.usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['creado_por_id'], ['configuracion.usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo', name='uq_entidades_bancarias_codigo'),
    schema='tesoreria'
    )
    op.create_index(op.f('ix_tesoreria_entidades_bancarias_id'), 'entidades_bancarias', ['id'], unique=False, schema='tesoreria')
    op.create_table('contrato',
    sa.Column('id_contrato', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('id_empleado', sa.BigInteger(), nullable=False),
    sa.Column('id_escala_salarial', sa.BigInteger(), nullable=True),
    sa.Column('id_cargo', sa.BigInteger(), nullable=False),
    sa.Column('tipo_contrato', sa.String(length=50), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.Column('sueldo_pactado', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('estado_contrato', sa.String(length=20), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_cargo'], ['rrhh.cargo.id_cargo'], ),
    sa.ForeignKeyConstraint(['id_empleado'], ['rrhh.empleado.id_empleado'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_escala_salarial'], ['rrhh.escala_salarial.id_escala'], ),
    sa.PrimaryKeyConstraint('id_contrato'),
    schema='rrhh'
    )
    op.create_table('empleado_carga_familiar',
    sa.Column('id_carga', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('id_empleado', sa.BigInteger(), nullable=False),
    sa.Column('identificacion', sa.String(length=20), nullable=True),
    sa.Column('nombres_completos', sa.String(length=200), nullable=False),
    sa.Column('parentesco', sa.String(length=50), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=False),
    sa.Column('aplica_deduccion_ir', sa.Boolean(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['id_empleado'], ['rrhh.empleado.id_empleado'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_carga'),
    schema='rrhh'
    )
    op.create_table('historial_laboral',
    sa.Column('id_historial', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('id_empleado', sa.BigInteger(), nullable=False),
    sa.Column('id_area', sa.BigInteger(), nullable=False),
    sa.Column('id_cargo', sa.BigInteger(), nullable=False),
    sa.Column('tipo_contrato', sa.String(length=50), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.Column('salario_acordado', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['id_area'], ['rrhh.area_organizacional.id_area'], ),
    sa.ForeignKeyConstraint(['id_cargo'], ['rrhh.cargo.id_cargo'], ),
    sa.ForeignKeyConstraint(['id_empleado'], ['rrhh.empleado.id_empleado'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_historial'),
    schema='rrhh'
    )
    op.create_table('certificados_presupuestarios',
    sa.Column('id_certificado', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('numero_certificado', sa.String(length=50), nullable=False),
    sa.Column('id_asignacion', sa.BigInteger(), nullable=False),
    sa.Column('monto_certificado', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('concepto', sa.Text(), nullable=False),
    sa.Column('fecha_solicitud', sa.Date(), nullable=False),
    sa.Column('fecha_certificacion', sa.Date(), nullable=True),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('motivo_anulacion', sa.Text(), nullable=True),
    sa.Column('referencia_tipo', sa.String(length=50), nullable=True),
    sa.Column('referencia_id', sa.BigInteger(), nullable=True),
    sa.Column('id_proceso_contratacion', sa.BigInteger(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_asignacion'], ['presupuesto.asignaciones_presupuestarias.id_asignacion'], ),
    sa.ForeignKeyConstraint(['id_proceso_contratacion'], ['contratacion.proceso_contratacion.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id_certificado'),
    sa.UniqueConstraint('numero_certificado', name='uq_certificado_numero'),
    schema='presupuesto'
    )
    op.create_index(op.f('ix_presupuesto_certificados_presupuestarios_numero_certificado'), 'certificados_presupuestarios', ['numero_certificado'], unique=False, schema='presupuesto')
    op.create_table('cajas_chicas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('monto_fijo', sa.Numeric(precision=18, scale=2), nullable=False, comment='Monto asignado del fondo fijo'),
    sa.Column('monto_disponible', sa.Numeric(precision=18, scale=2), nullable=False, comment='Saldo actual disponible'),
    sa.Column('cuenta_contable_id', sa.Integer(), nullable=True),
    sa.Column('responsable_id', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(length=10), nullable=False, comment='ABIERTA | CERRADA'),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('creado_por_id', sa.Integer(), nullable=True),
    sa.Column('actualizado_por_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['actualizado_por_id'], ['configuracion.usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['creado_por_id'], ['configuracion.usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['cuenta_contable_id'], ['contabilidad.cuentas_contables.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['responsable_id'], ['configuracion.usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo', name='uq_cajas_chicas_codigo'),
    schema='tesoreria'
    )
    op.create_index(op.f('ix_tesoreria_cajas_chicas_id'), 'cajas_chicas', ['id'], unique=False, schema='tesoreria')
    op.create_table('cuentas_bancarias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entidad_bancaria_id', sa.Integer(), nullable=False),
    sa.Column('numero_cuenta', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False, comment='Nombre descriptivo de la cuenta'),
    sa.Column('tipo', sa.String(length=20), nullable=False, comment='CORRIENTE|AHORROS|RECAUDACION|PAGOS'),
    sa.Column('moneda', sa.String(length=3), nullable=False),
    sa.Column('cuenta_contable_id', sa.Integer(), nullable=True, comment='Cuenta contable asociada para asientos automáticos'),
    sa.Column('saldo_inicial', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('es_activa', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('creado_por_id', sa.Integer(), nullable=True),
    sa.Column('actualizado_por_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['actualizado_por_id'], ['configuracion.usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['creado_por_id'], ['configuracion.usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['cuenta_contable_id'], ['contabilidad.cuentas_contables.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['entidad_bancaria_id'], ['tesoreria.entidades_bancarias.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_cuenta', name='uq_cuentas_bancarias_numero'),
    schema='tesoreria'
    )
    op.create_index(op.f('ix_tesoreria_cuentas_bancarias_id'), 'cuentas_bancarias', ['id'], unique=False, schema='tesoreria')
    op.create_index(op.f('ix_tesoreria_cuentas_bancarias_numero_cuenta'), 'cuentas_bancarias', ['numero_cuenta'], unique=False, schema='tesoreria')
    op.create_table('compromisos',
    sa.Column('id_compromiso', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('id_certificado', sa.BigInteger(), nullable=False),
    sa.Column('numero_compromiso', sa.String(length=50), nullable=False),
    sa.Column('monto_comprometido', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('concepto', sa.Text(), nullable=False),
    sa.Column('fecha_compromiso', sa.Date(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('motivo_anulacion', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_certificado'], ['presupuesto.certificados_presupuestarios.id_certificado'], ),
    sa.PrimaryKeyConstraint('id_compromiso'),
    schema='presupuesto'
    )
    op.create_index(op.f('ix_presupuesto_compromisos_numero_compromiso'), 'compromisos', ['numero_compromiso'], unique=False, schema='presupuesto')
    op.create_table('extractos_bancarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cuenta_bancaria_id', sa.Integer(), nullable=False),
    sa.Column('referencia', sa.String(length=100), nullable=True, comment='Número de extracto del banco'),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('saldo_inicial', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('saldo_final', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('estado', sa.String(length=15), nullable=False, comment='BORRADOR | CONFIRMADO | CERRADO'),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('creado_por_id', sa.Integer(), nullable=True),
    sa.Column('actualizado_por_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['actualizado_por_id'], ['configuracion.usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['creado_por_id'], ['configuracion.usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['cuenta_bancaria_id'], ['tesoreria.cuentas_bancarias.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cuenta_bancaria_id', 'fecha_inicio', 'fecha_fin', name='uq_extracto_cuenta_periodo'),
    schema='tesoreria'
    )
    op.create_index(op.f('ix_tesoreria_extractos_bancarios_id'), 'extractos_bancarios', ['id'], unique=False, schema='tesoreria')
    op.create_table('cierres_recaudacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False, comment='RN-F02: UNIQUE — un solo cierre por día'),
    sa.Column('total_recaudado', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('numero_transacciones', sa.Integer(), nullable=False),
    sa.Column('asiento_recaudacion_id', sa.Integer(), nullable=True, comment='RN-F03: asiento de recaudación del día'),
    sa.Column('asiento_traslado_bce_id', sa.Integer(), nullable=True, comment='RN-F03: asiento de traslado a BCE'),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('creado_por_id', sa.Integer(), nullable=True),
    sa.Column('actualizado_por_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['actualizado_por_id'], ['configuracion.usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['asiento_recaudacion_id'], ['contabilidad.asientos_contables.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['asiento_traslado_bce_id'], ['contabilidad.asientos_contables.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['creado_por_id'], ['configuracion.usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fecha'),
    sa.UniqueConstraint('fecha', name='uq_cierre_recaudacion_fecha'),
    schema='financiero'
    )
    op.create_index(op.f('ix_financiero_cierres_recaudacion_id'), 'cierres_recaudacion', ['id'], unique=False, schema='financiero')
    op.create_table('facturas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=50), nullable=False, comment='Número secuencial generado al aprobar'),
    sa.Column('tipo_documento_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=15), nullable=False, comment='CLIENTE (AR) | PROVEEDOR (AP)'),
    sa.Column('estado', sa.String(length=10), nullable=False, comment='BORRADOR|APROBADA|PAGADA|PARCIAL|ANULADA (RN-F04)'),
    sa.Column('tercero_id', sa.Integer(), nullable=True, comment='ID del ciudadano o proveedor según tipo'),
    sa.Column('nombre_tercero', sa.String(length=200), nullable=False, comment='Nombre guardado al momento de emisión'),
    sa.Column('identificacion_tercero', sa.String(length=20), nullable=False, comment='RUC/CI del tercero'),
    sa.Column('fecha_emision', sa.Date(), nullable=False),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('descuento', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('base_imponible', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_iva', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('saldo_pendiente', sa.Numeric(precision=18, scale=2), nullable=False, comment='total - pagos aplicados'),
    sa.Column('clave_acceso_sri', sa.String(length=49), nullable=True, comment='Clave de acceso del comprobante electrónico SRI'),
    sa.Column('numero_autorizacion_sri', sa.String(length=49), nullable=True),
    sa.Column('asiento_contable_id', sa.Integer(), nullable=True, comment='RN-F05: asiento contable generado automáticamente al aprobar'),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('motivo_anulacion', sa.Text(), nullable=True, comment='RN-F04: motivo del estado ANULADA'),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('creado_por_id', sa.Integer(), nullable=True),
    sa.Column('actualizado_por_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['actualizado_por_id'], ['configuracion.usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['asiento_contable_id'], ['contabilidad.asientos_contables.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['creado_por_id'], ['configuracion.usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tipo_documento_id'], ['financiero.tipos_documento.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero', name='uq_facturas_numero'),
    schema='financiero'
    )
    op.create_index(op.f('ix_financiero_facturas_id'), 'facturas', ['id'], unique=False, schema='financiero')
    op.create_index(op.f('ix_financiero_facturas_numero'), 'facturas', ['numero'], unique=False, schema='financiero')
    op.create_table('pagos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=50), nullable=False),
    sa.Column('tipo', sa.String(length=15), nullable=False, comment='CLIENTE (cobro AR) | PROVEEDOR (pago AP)'),
    sa.Column('estado', sa.String(length=15), nullable=False, comment='BORRADOR|CONFIRMADO|ANULADO (RN-F04)'),
    sa.Column('tercero_id', sa.Integer(), nullable=True),
    sa.Column('nombre_tercero', sa.String(length=200), nullable=False),
    sa.Column('identificacion_tercero', sa.String(length=20), nullable=False),
    sa.Column('fecha_pago', sa.Date(), nullable=False),
    sa.Column('tipo_pago', sa.String(length=20), nullable=False, comment='EFECTIVO|CHEQUE|TRANSFERENCIA|SPI|BCE|NOTA_CREDITO'),
    sa.Column('cuenta_bancaria_id', sa.Integer(), nullable=True),
    sa.Column('monto_total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('referencia_bancaria', sa.String(length=100), nullable=True, comment='Número de transacción SPI/BCE/cheque'),
    sa.Column('asiento_contable_id', sa.Integer(), nullable=True, comment='RN-F05: asiento contable generado automáticamente al confirmar'),
    sa.Column('asiento_traslado_id', sa.Integer(), nullable=True, comment='RN-F03: asiento de traslado BCE (recaudación → CUT)'),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('motivo_anulacion', sa.Text(), nullable=True, comment='RN-F04'),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('creado_por_id', sa.Integer(), nullable=True),
    sa.Column('actualizado_por_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['actualizado_por_id'], ['configuracion.usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['asiento_contable_id'], ['contabilidad.asientos_contables.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['asiento_traslado_id'], ['contabilidad.asientos_contables.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['creado_por_id'], ['configuracion.usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['cuenta_bancaria_id'], ['tesoreria.cuentas_bancarias.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero', name='uq_pagos_numero'),
    schema='financiero'
    )
    op.create_index(op.f('ix_financiero_pagos_id'), 'pagos', ['id'], unique=False, schema='financiero')
    op.create_index(op.f('ix_financiero_pagos_numero'), 'pagos', ['numero'], unique=False, schema='financiero')
    op.create_table('conciliaciones_bancarias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cuenta_bancaria_id', sa.Integer(), nullable=False),
    sa.Column('extracto_id', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=100), nullable=False, comment='Nombre descriptivo del proceso'),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('saldo_libro', sa.Numeric(precision=18, scale=2), nullable=False, comment='Saldo según libros contables'),
    sa.Column('saldo_banco', sa.Numeric(precision=18, scale=2), nullable=False, comment='Saldo según extracto bancario'),
    sa.Column('diferencia', sa.Numeric(precision=18, scale=2), nullable=False, comment='saldo_banco - saldo_libro'),
    sa.Column('estado', sa.String(length=10), nullable=False, comment='ABIERTO | CERRADO (RN-T04: CERRADO es definitivo)'),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('creado_por_id', sa.Integer(), nullable=True),
    sa.Column('actualizado_por_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['actualizado_por_id'], ['configuracion.usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['creado_por_id'], ['configuracion.usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['cuenta_bancaria_id'], ['tesoreria.cuentas_bancarias.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['extracto_id'], ['tesoreria.extractos_bancarios.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    schema='tesoreria'
    )
    op.create_index(op.f('ix_tesoreria_conciliaciones_bancarias_id'), 'conciliaciones_bancarias', ['id'], unique=False, schema='tesoreria')
    op.create_table('lineas_extracto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('extracto_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('tipo_transaccion', sa.String(length=20), nullable=False, comment='IESS|SRI|BCE|SPI|TRANSFERENCIA|CHEQUE|...'),
    sa.Column('referencia', sa.String(length=100), nullable=True, comment='Número de transacción del banco'),
    sa.Column('descripcion', sa.String(length=500), nullable=True),
    sa.Column('valor', sa.Numeric(precision=18, scale=2), nullable=False, comment='Positivo = crédito (ingreso), negativo = débito (salida)'),
    sa.Column('esta_conciliada', sa.Boolean(), nullable=False, comment='RN-T01: marcado por el proceso de conciliación'),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('creado_por_id', sa.Integer(), nullable=True),
    sa.Column('actualizado_por_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['actualizado_por_id'], ['configuracion.usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['creado_por_id'], ['configuracion.usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['extracto_id'], ['tesoreria.extractos_bancarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='tesoreria'
    )
    op.create_index(op.f('ix_tesoreria_lineas_extracto_id'), 'lineas_extracto', ['id'], unique=False, schema='tesoreria')
    op.create_table('movimientos_caja',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('caja_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('tipo', sa.String(length=15), nullable=False, comment='INGRESO|EGRESO|APERTURA|CIERRE'),
    sa.Column('concepto', sa.String(length=500), nullable=False),
    sa.Column('monto', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('numero_comprobante', sa.String(length=50), nullable=True),
    sa.Column('beneficiario', sa.String(length=200), nullable=True),
    sa.Column('asiento_contable_id', sa.Integer(), nullable=True, comment='RN-T05: asiento contable generado automáticamente'),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('creado_por_id', sa.Integer(), nullable=True),
    sa.Column('actualizado_por_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('monto > 0', name='chk_movimiento_monto_positivo'),
    sa.ForeignKeyConstraint(['actualizado_por_id'], ['configuracion.usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['asiento_contable_id'], ['contabilidad.asientos_contables.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['caja_id'], ['tesoreria.cajas_chicas.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['creado_por_id'], ['configuracion.usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='tesoreria'
    )
    op.create_index(op.f('ix_tesoreria_movimientos_caja_id'), 'movimientos_caja', ['id'], unique=False, schema='tesoreria')
    op.create_table('lineas_factura',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('factura_id', sa.Integer(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=False),
    sa.Column('cuenta_contable_id', sa.Integer(), nullable=True, comment='Cuenta para el asiento automático'),
    sa.Column('cantidad', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('descuento_linea', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('tipo_impuesto', sa.String(length=10), nullable=False, comment='IVA_15|IVA_12|IVA_5|IVA_0|EXENTO|ICE'),
    sa.Column('porcentaje_impuesto', sa.Numeric(precision=5, scale=2), nullable=False, comment='Porcentaje del impuesto: 15, 12, 5, 0'),
    sa.Column('subtotal_linea', sa.Numeric(precision=18, scale=2), nullable=False, comment='cantidad * precio_unitario - descuento_linea'),
    sa.Column('valor_impuesto', sa.Numeric(precision=18, scale=2), nullable=False, comment='subtotal_linea * porcentaje_impuesto / 100'),
    sa.Column('total_linea', sa.Numeric(precision=18, scale=2), nullable=False, comment='subtotal_linea + valor_impuesto'),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('creado_por_id', sa.Integer(), nullable=True),
    sa.Column('actualizado_por_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('cantidad > 0', name='chk_linea_factura_cantidad_positiva'),
    sa.CheckConstraint('precio_unitario >= 0', name='chk_linea_factura_precio_no_negativo'),
    sa.ForeignKeyConstraint(['actualizado_por_id'], ['configuracion.usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['creado_por_id'], ['configuracion.usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['cuenta_contable_id'], ['contabilidad.cuentas_contables.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['factura_id'], ['financiero.facturas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='financiero'
    )
    op.create_index(op.f('ix_financiero_lineas_factura_id'), 'lineas_factura', ['id'], unique=False, schema='financiero')
    op.create_table('lineas_pago',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pago_id', sa.Integer(), nullable=False),
    sa.Column('factura_id', sa.Integer(), nullable=False),
    sa.Column('monto_aplicado', sa.Numeric(precision=18, scale=2), nullable=False, comment='Monto de este pago aplicado a esta factura'),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('creado_por_id', sa.Integer(), nullable=True),
    sa.Column('actualizado_por_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('monto_aplicado > 0', name='chk_linea_pago_monto_positivo'),
    sa.ForeignKeyConstraint(['actualizado_por_id'], ['configuracion.usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['creado_por_id'], ['configuracion.usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['factura_id'], ['financiero.facturas.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['pago_id'], ['financiero.pagos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='financiero'
    )
    op.create_index(op.f('ix_financiero_lineas_pago_id'), 'lineas_pago', ['id'], unique=False, schema='financiero')
    op.create_table('devengados',
    sa.Column('id_devengado', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('id_compromiso', sa.BigInteger(), nullable=False),
    sa.Column('numero_devengado', sa.String(length=50), nullable=False),
    sa.Column('monto_devengado', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('concepto', sa.Text(), nullable=False),
    sa.Column('fecha_devengado', sa.Date(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('id_asiento_contable', sa.BigInteger(), nullable=True),
    sa.Column('id_factura', sa.BigInteger(), nullable=True),
    sa.Column('motivo_anulacion', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_asiento_contable'], ['contabilidad.asientos_contables.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_compromiso'], ['presupuesto.compromisos.id_compromiso'], ),
    sa.ForeignKeyConstraint(['id_factura'], ['financiero.facturas.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id_devengado'),
    schema='presupuesto'
    )
    op.create_index(op.f('ix_presupuesto_devengados_numero_devengado'), 'devengados', ['numero_devengado'], unique=False, schema='presupuesto')
    op.create_table('marcas_conciliacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conciliacion_id', sa.Integer(), nullable=False),
    sa.Column('linea_extracto_id', sa.Integer(), nullable=False),
    sa.Column('asiento_contable_id', sa.Integer(), nullable=True, comment='Asiento contable que originó esta transacción'),
    sa.Column('valor_conciliado', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('observacion', sa.String(length=255), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('creado_por_id', sa.Integer(), nullable=True),
    sa.Column('actualizado_por_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['actualizado_por_id'], ['configuracion.usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['asiento_contable_id'], ['contabilidad.asientos_contables.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['conciliacion_id'], ['tesoreria.conciliaciones_bancarias.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['creado_por_id'], ['configuracion.usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['linea_extracto_id'], ['tesoreria.lineas_extracto.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('linea_extracto_id', name='uq_marca_linea_extracto'),
    schema='tesoreria'
    )
    op.create_index(op.f('ix_tesoreria_marcas_conciliacion_id'), 'marcas_conciliacion', ['id'], unique=False, schema='tesoreria')
    op.drop_column('puestos', 'escala_ocupacional', schema='administracion')
    op.drop_column('puestos', 'remuneracion_mensual', schema='administracion')
    op.add_column('titulos_profesionales', sa.Column('empleado_id', sa.Integer(), nullable=False), schema='administracion')
    op.add_column('titulos_profesionales', sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False), schema='administracion')
    op.add_column('titulos_profesionales', sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False), schema='administracion')
    op.add_column('titulos_profesionales', sa.Column('creado_por_id', sa.Integer(), nullable=True), schema='administracion')
    op.add_column('titulos_profesionales', sa.Column('actualizado_por_id', sa.Integer(), nullable=True), schema='administracion')
    op.create_foreign_key(None, 'titulos_profesionales', 'usuarios', ['creado_por_id'], ['id'], source_schema='administracion', referent_schema='configuracion', ondelete='SET NULL')
    op.create_foreign_key(None, 'titulos_profesionales', 'usuarios', ['actualizado_por_id'], ['id'], source_schema='administracion', referent_schema='configuracion', ondelete='SET NULL')
    op.drop_column('titulos_profesionales', 'nivel', schema='administracion')
    op.drop_column('titulos_profesionales', 'personal_id', schema='administracion')
    op.alter_column('asientos_contables', 'numero',
               existing_type=sa.VARCHAR(length=30),
               comment='Número secuencial generado al publicar: DIARIO/PERIODO/SEQ',
               existing_nullable=False,
               schema='contabilidad')
    op.alter_column('asientos_contables', 'referencia',
               existing_type=sa.VARCHAR(length=100),
               comment='Número de documento origen (factura, cheque, etc.)',
               existing_nullable=True,
               schema='contabilidad')
    op.alter_column('asientos_contables', 'concepto',
               existing_type=sa.TEXT(),
               comment='Descripción del asiento',
               existing_nullable=False,
               schema='contabilidad')
    op.alter_column('asientos_contables', 'estado',
               existing_type=sa.VARCHAR(length=10),
               server_default=None,
               comment='BORRADOR | PUBLICADO | ANULADO (RN-11)',
               existing_nullable=False,
               schema='contabilidad')
    op.alter_column('asientos_contables', 'total_debe',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               server_default=None,
               comment='Suma de todos los débitos de las líneas',
               existing_nullable=False,
               schema='contabilidad')
    op.alter_column('asientos_contables', 'total_haber',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               server_default=None,
               comment='Suma de todos los créditos de las líneas',
               existing_nullable=False,
               schema='contabilidad')
    op.alter_column('asientos_contables', 'motivo_anulacion',
               existing_type=sa.TEXT(),
               comment='RN-11: razón del estado ANULADO',
               existing_nullable=True,
               schema='contabilidad')
    op.alter_column('cuentas_contables', 'codigo',
               existing_type=sa.VARCHAR(length=50),
               comment='Código jerárquico SIGEF, ej: 1.1.1.01.01.001',
               existing_nullable=False,
               schema='contabilidad')
    op.alter_column('cuentas_contables', 'cuenta_padre_id',
               existing_type=sa.INTEGER(),
               comment='NULL para cuentas raíz (nivel 1)',
               existing_nullable=True,
               schema='contabilidad')
    op.alter_column('cuentas_contables', 'nivel',
               existing_type=sa.INTEGER(),
               comment='Nivel jerárquico 1-10',
               existing_nullable=False,
               schema='contabilidad')
    op.alter_column('cuentas_contables', 'es_hoja',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               comment='True = cuenta de detalle que acepta movimientos',
               existing_nullable=False,
               schema='contabilidad')
    op.alter_column('cuentas_contables', 'permite_movimientos',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               comment='Solo True en cuentas hoja',
               existing_nullable=False,
               schema='contabilidad')
    op.alter_column('cuentas_contables', 'partida_presupuestaria',
               existing_type=sa.VARCHAR(length=100),
               comment='RN-02: vínculo con partida presupuestaria SIGEF',
               existing_nullable=True,
               schema='contabilidad')
    op.alter_column('cuentas_contables', 'estado',
               existing_type=sa.VARCHAR(length=10),
               server_default=None,
               comment='ACTIVA | INACTIVA',
               existing_nullable=False,
               schema='contabilidad')
    op.alter_column('diarios', 'tipo',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               comment='GENERAL|VENTAS|COMPRAS|BANCO|CAJA|APERTURA|CIERRE|AJUSTE',
               existing_nullable=False,
               schema='contabilidad')
    op.alter_column('diarios', 'cuenta_default_id',
               existing_type=sa.INTEGER(),
               comment='Cuenta contraparte por defecto para este diario',
               existing_nullable=True,
               schema='contabilidad')
    op.alter_column('diarios', 'es_activo',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False,
               schema='contabilidad')
    op.alter_column('lineas_asiento', 'debe',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               server_default=None,
               comment='Valor débito (solo uno de debe/haber puede ser > 0)',
               existing_nullable=False,
               schema='contabilidad')
    op.alter_column('lineas_asiento', 'haber',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               server_default=None,
               comment='Valor crédito (solo uno de debe/haber puede ser > 0)',
               existing_nullable=False,
               schema='contabilidad')
    op.alter_column('lineas_asiento', 'orden',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               schema='contabilidad')
    op.alter_column('parametros_contables', 'clave',
               existing_type=sa.VARCHAR(length=50),
               comment='Identificador único del parámetro, ej: CUENTA_CXC',
               existing_nullable=False,
               schema='contabilidad')
    op.alter_column('parametros_contables', 'cuenta_id',
               existing_type=sa.INTEGER(),
               comment='Cuenta contable asociada (NULL si es parámetro de diario)',
               existing_nullable=True,
               schema='contabilidad')
    op.alter_column('parametros_contables', 'diario_id',
               existing_type=sa.INTEGER(),
               comment='Diario asociado (NULL si es parámetro de cuenta)',
               existing_nullable=True,
               schema='contabilidad')
    op.alter_column('parametros_contables', 'creado_en',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'),
               schema='contabilidad')
    op.alter_column('parametros_contables', 'actualizado_en',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'),
               schema='contabilidad')
    op.drop_index(op.f('ix_parametros_contables_clave'), table_name='parametros_contables', schema='contabilidad')
    op.create_index(op.f('ix_contabilidad_parametros_contables_clave'), 'parametros_contables', ['clave'], unique=False, schema='contabilidad')
    op.create_index(op.f('ix_contabilidad_parametros_contables_id'), 'parametros_contables', ['id'], unique=False, schema='contabilidad')
    op.alter_column('periodos_contables', 'nombre',
               existing_type=sa.VARCHAR(length=50),
               comment='Ej: Enero 2026',
               existing_nullable=False,
               schema='contabilidad')
    op.alter_column('periodos_contables', 'estado',
               existing_type=sa.VARCHAR(length=10),
               server_default=None,
               comment='ABIERTO | CERRADO | BLOQUEADO',
               existing_nullable=False,
               schema='contabilidad')
    op.alter_column('tipos_cuenta', 'naturaleza',
               existing_type=sa.VARCHAR(length=10),
               comment='DEUDORA (activo/gasto) o ACREEDORA (pasivo/patrimonio/ingreso)',
               existing_comment='DEUDORA o ACREEDORA',
               existing_nullable=False,
               schema='contabilidad')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tipos_cuenta', 'naturaleza',
               existing_type=sa.VARCHAR(length=10),
               comment='DEUDORA o ACREEDORA',
               existing_comment='DEUDORA (activo/gasto) o ACREEDORA (pasivo/patrimonio/ingreso)',
               existing_nullable=False,
               schema='contabilidad')
    op.alter_column('periodos_contables', 'estado',
               existing_type=sa.VARCHAR(length=10),
               server_default=sa.text("'ABIERTO'::character varying"),
               comment=None,
               existing_comment='ABIERTO | CERRADO | BLOQUEADO',
               existing_nullable=False,
               schema='contabilidad')
    op.alter_column('periodos_contables', 'nombre',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Ej: Enero 2026',
               existing_nullable=False,
               schema='contabilidad')
    op.drop_index(op.f('ix_contabilidad_parametros_contables_id'), table_name='parametros_contables', schema='contabilidad')
    op.drop_index(op.f('ix_contabilidad_parametros_contables_clave'), table_name='parametros_contables', schema='contabilidad')
    op.create_index(op.f('ix_parametros_contables_clave'), 'parametros_contables', ['clave'], unique=False, schema='contabilidad')
    op.alter_column('parametros_contables', 'actualizado_en',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'),
               schema='contabilidad')
    op.alter_column('parametros_contables', 'creado_en',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'),
               schema='contabilidad')
    op.alter_column('parametros_contables', 'diario_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Diario asociado (NULL si es parámetro de cuenta)',
               existing_nullable=True,
               schema='contabilidad')
    op.alter_column('parametros_contables', 'cuenta_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Cuenta contable asociada (NULL si es parámetro de diario)',
               existing_nullable=True,
               schema='contabilidad')
    op.alter_column('parametros_contables', 'clave',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Identificador único del parámetro, ej: CUENTA_CXC',
               existing_nullable=False,
               schema='contabilidad')
    op.alter_column('lineas_asiento', 'orden',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               existing_nullable=False,
               schema='contabilidad')
    op.alter_column('lineas_asiento', 'haber',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               server_default=sa.text("'0'::numeric"),
               comment=None,
               existing_comment='Valor crédito (solo uno de debe/haber puede ser > 0)',
               existing_nullable=False,
               schema='contabilidad')
    op.alter_column('lineas_asiento', 'debe',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               server_default=sa.text("'0'::numeric"),
               comment=None,
               existing_comment='Valor débito (solo uno de debe/haber puede ser > 0)',
               existing_nullable=False,
               schema='contabilidad')
    op.alter_column('diarios', 'es_activo',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False,
               schema='contabilidad')
    op.alter_column('diarios', 'cuenta_default_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Cuenta contraparte por defecto para este diario',
               existing_nullable=True,
               schema='contabilidad')
    op.alter_column('diarios', 'tipo',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'GENERAL'::character varying"),
               comment=None,
               existing_comment='GENERAL|VENTAS|COMPRAS|BANCO|CAJA|APERTURA|CIERRE|AJUSTE',
               existing_nullable=False,
               schema='contabilidad')
    op.alter_column('cuentas_contables', 'estado',
               existing_type=sa.VARCHAR(length=10),
               server_default=sa.text("'ACTIVA'::character varying"),
               comment=None,
               existing_comment='ACTIVA | INACTIVA',
               existing_nullable=False,
               schema='contabilidad')
    op.alter_column('cuentas_contables', 'partida_presupuestaria',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='RN-02: vínculo con partida presupuestaria SIGEF',
               existing_nullable=True,
               schema='contabilidad')
    op.alter_column('cuentas_contables', 'permite_movimientos',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               comment=None,
               existing_comment='Solo True en cuentas hoja',
               existing_nullable=False,
               schema='contabilidad')
    op.alter_column('cuentas_contables', 'es_hoja',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               comment=None,
               existing_comment='True = cuenta de detalle que acepta movimientos',
               existing_nullable=False,
               schema='contabilidad')
    op.alter_column('cuentas_contables', 'nivel',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Nivel jerárquico 1-10',
               existing_nullable=False,
               schema='contabilidad')
    op.alter_column('cuentas_contables', 'cuenta_padre_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='NULL para cuentas raíz (nivel 1)',
               existing_nullable=True,
               schema='contabilidad')
    op.alter_column('cuentas_contables', 'codigo',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Código jerárquico SIGEF, ej: 1.1.1.01.01.001',
               existing_nullable=False,
               schema='contabilidad')
    op.alter_column('asientos_contables', 'motivo_anulacion',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='RN-11: razón del estado ANULADO',
               existing_nullable=True,
               schema='contabilidad')
    op.alter_column('asientos_contables', 'total_haber',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               server_default=sa.text("'0'::numeric"),
               comment=None,
               existing_comment='Suma de todos los créditos de las líneas',
               existing_nullable=False,
               schema='contabilidad')
    op.alter_column('asientos_contables', 'total_debe',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               server_default=sa.text("'0'::numeric"),
               comment=None,
               existing_comment='Suma de todos los débitos de las líneas',
               existing_nullable=False,
               schema='contabilidad')
    op.alter_column('asientos_contables', 'estado',
               existing_type=sa.VARCHAR(length=10),
               server_default=sa.text("'BORRADOR'::character varying"),
               comment=None,
               existing_comment='BORRADOR | PUBLICADO | ANULADO (RN-11)',
               existing_nullable=False,
               schema='contabilidad')
    op.alter_column('asientos_contables', 'concepto',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Descripción del asiento',
               existing_nullable=False,
               schema='contabilidad')
    op.alter_column('asientos_contables', 'referencia',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Número de documento origen (factura, cheque, etc.)',
               existing_nullable=True,
               schema='contabilidad')
    op.alter_column('asientos_contables', 'numero',
               existing_type=sa.VARCHAR(length=30),
               comment=None,
               existing_comment='Número secuencial generado al publicar: DIARIO/PERIODO/SEQ',
               existing_nullable=False,
               schema='contabilidad')
    op.add_column('titulos_profesionales', sa.Column('personal_id', sa.INTEGER(), autoincrement=False, nullable=False), schema='administracion')
    op.add_column('titulos_profesionales', sa.Column('nivel', postgresql.ENUM('TECNICO', 'TECNOLOGICO', 'TERCER_NIVEL', 'CUARTO_NIVEL', 'PHD', name='nivel_educacion'), autoincrement=False, nullable=False), schema='administracion')
    op.drop_constraint(None, 'titulos_profesionales', schema='administracion', type_='foreignkey')
    op.drop_constraint(None, 'titulos_profesionales', schema='administracion', type_='foreignkey')
    op.drop_column('titulos_profesionales', 'actualizado_por_id', schema='administracion')
    op.drop_column('titulos_profesionales', 'creado_por_id', schema='administracion')
    op.drop_column('titulos_profesionales', 'actualizado_en', schema='administracion')
    op.drop_column('titulos_profesionales', 'creado_en', schema='administracion')
    op.drop_column('titulos_profesionales', 'empleado_id', schema='administracion')
    op.add_column('puestos', sa.Column('remuneracion_mensual', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False), schema='administracion')
    op.add_column('puestos', sa.Column('escala_ocupacional', sa.VARCHAR(length=100), autoincrement=False, nullable=True), schema='administracion')
    op.drop_index(op.f('ix_tesoreria_marcas_conciliacion_id'), table_name='marcas_conciliacion', schema='tesoreria')
    op.drop_table('marcas_conciliacion', schema='tesoreria')
    op.drop_index(op.f('ix_presupuesto_devengados_numero_devengado'), table_name='devengados', schema='presupuesto')
    op.drop_table('devengados', schema='presupuesto')
    op.drop_index(op.f('ix_financiero_lineas_pago_id'), table_name='lineas_pago', schema='financiero')
    op.drop_table('lineas_pago', schema='financiero')
    op.drop_index(op.f('ix_financiero_lineas_factura_id'), table_name='lineas_factura', schema='financiero')
    op.drop_table('lineas_factura', schema='financiero')
    op.drop_index(op.f('ix_tesoreria_movimientos_caja_id'), table_name='movimientos_caja', schema='tesoreria')
    op.drop_table('movimientos_caja', schema='tesoreria')
    op.drop_index(op.f('ix_tesoreria_lineas_extracto_id'), table_name='lineas_extracto', schema='tesoreria')
    op.drop_table('lineas_extracto', schema='tesoreria')
    op.drop_index(op.f('ix_tesoreria_conciliaciones_bancarias_id'), table_name='conciliaciones_bancarias', schema='tesoreria')
    op.drop_table('conciliaciones_bancarias', schema='tesoreria')
    op.drop_index(op.f('ix_financiero_pagos_numero'), table_name='pagos', schema='financiero')
    op.drop_index(op.f('ix_financiero_pagos_id'), table_name='pagos', schema='financiero')
    op.drop_table('pagos', schema='financiero')
    op.drop_index(op.f('ix_financiero_facturas_numero'), table_name='facturas', schema='financiero')
    op.drop_index(op.f('ix_financiero_facturas_id'), table_name='facturas', schema='financiero')
    op.drop_table('facturas', schema='financiero')
    op.drop_index(op.f('ix_financiero_cierres_recaudacion_id'), table_name='cierres_recaudacion', schema='financiero')
    op.drop_table('cierres_recaudacion', schema='financiero')
    op.drop_index(op.f('ix_tesoreria_extractos_bancarios_id'), table_name='extractos_bancarios', schema='tesoreria')
    op.drop_table('extractos_bancarios', schema='tesoreria')
    op.drop_index(op.f('ix_presupuesto_compromisos_numero_compromiso'), table_name='compromisos', schema='presupuesto')
    op.drop_table('compromisos', schema='presupuesto')
    op.drop_index(op.f('ix_tesoreria_cuentas_bancarias_numero_cuenta'), table_name='cuentas_bancarias', schema='tesoreria')
    op.drop_index(op.f('ix_tesoreria_cuentas_bancarias_id'), table_name='cuentas_bancarias', schema='tesoreria')
    op.drop_table('cuentas_bancarias', schema='tesoreria')
    op.drop_index(op.f('ix_tesoreria_cajas_chicas_id'), table_name='cajas_chicas', schema='tesoreria')
    op.drop_table('cajas_chicas', schema='tesoreria')
    op.drop_index(op.f('ix_presupuesto_certificados_presupuestarios_numero_certificado'), table_name='certificados_presupuestarios', schema='presupuesto')
    op.drop_table('certificados_presupuestarios', schema='presupuesto')
    op.drop_table('historial_laboral', schema='rrhh')
    op.drop_table('empleado_carga_familiar', schema='rrhh')
    op.drop_table('contrato', schema='rrhh')
    op.drop_index(op.f('ix_tesoreria_entidades_bancarias_id'), table_name='entidades_bancarias', schema='tesoreria')
    op.drop_table('entidades_bancarias', schema='tesoreria')
    op.drop_index(op.f('ix_rrhh_empleado_identificacion'), table_name='empleado', schema='rrhh')
    op.drop_table('empleado', schema='rrhh')
    op.drop_table('reformas_presupuestarias', schema='presupuesto')
    op.drop_index(op.f('ix_financiero_tipos_documento_id'), table_name='tipos_documento', schema='financiero')
    op.drop_table('tipos_documento', schema='financiero')
    op.drop_table('cargo', schema='rrhh')
    op.drop_table('asignaciones_presupuestarias', schema='presupuesto')
    op.drop_table('rubro_nomina', schema='rrhh')
    op.drop_table('parametro_calculo', schema='rrhh')
    op.drop_table('impuesto_renta_escala', schema='rrhh')
    op.drop_table('escala_salarial', schema='rrhh')
    op.drop_table('area_organizacional', schema='rrhh')
    op.drop_index(op.f('ix_presupuesto_presupuestos_anuales_anio_fiscal'), table_name='presupuestos_anuales', schema='presupuesto')
    op.drop_table('presupuestos_anuales', schema='presupuesto')
    op.drop_index(op.f('ix_presupuesto_partidas_presupuestarias_codigo'), table_name='partidas_presupuestarias', schema='presupuesto')
    op.drop_table('partidas_presupuestarias', schema='presupuesto')
    # ### end Alembic commands ###
