"""Creacion Fase 4 Predios Cuentas Historial

Revision ID: aa1f73fc182c
Revises: 3d5bf4738387
Create Date: 2026-03-03 03:40:46.421244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'aa1f73fc182c'
down_revision: Union[str, Sequence[str], None] = '3d5bf4738387'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medidores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('marca', sa.String(length=50), nullable=True),
    sa.Column('serie', sa.String(length=50), nullable=False),
    sa.Column('esferas', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('creado_por_id', sa.Integer(), nullable=True),
    sa.Column('actualizado_por_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['actualizado_por_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['creado_por_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medidores_id'), 'medidores', ['id'], unique=False)
    op.create_index(op.f('ix_medidores_serie'), 'medidores', ['serie'], unique=True)
    op.create_table('predios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clave_catastral', sa.String(length=50), nullable=False),
    sa.Column('barrio_id', sa.Integer(), nullable=True),
    sa.Column('calle_principal_id', sa.Integer(), nullable=True),
    sa.Column('calle_secundaria_id', sa.Integer(), nullable=True),
    sa.Column('numero_casa', sa.String(length=50), nullable=True),
    sa.Column('geometria', geoalchemy2.types.Geometry(srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('creado_por_id', sa.Integer(), nullable=True),
    sa.Column('actualizado_por_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['actualizado_por_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['barrio_id'], ['barrios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['calle_principal_id'], ['calles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['calle_secundaria_id'], ['calles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['creado_por_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute('CREATE INDEX IF NOT EXISTS idx_predios_geometria ON predios USING gist (geometria)')
    op.create_index(op.f('ix_predios_clave_catastral'), 'predios', ['clave_catastral'], unique=True)
    op.create_index(op.f('ix_predios_id'), 'predios', ['id'], unique=False)
    op.create_table('acometidas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('predio_id', sa.Integer(), nullable=False),
    sa.Column('ruta_id', sa.Integer(), nullable=True),
    sa.Column('diametro', sa.Float(), nullable=True),
    sa.Column('material', sa.String(length=50), nullable=True),
    sa.Column('geometria', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('creado_por_id', sa.Integer(), nullable=True),
    sa.Column('actualizado_por_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['actualizado_por_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['creado_por_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['predio_id'], ['predios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ruta_id'], ['rutas.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute('CREATE INDEX IF NOT EXISTS idx_acometidas_geometria ON acometidas USING gist (geometria)')
    op.create_index(op.f('ix_acometidas_id'), 'acometidas', ['id'], unique=False)
    op.create_table('cuentas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('acometida_id', sa.Integer(), nullable=False),
    sa.Column('propietario_id', sa.Integer(), nullable=False),
    sa.Column('responsable_pago_id', sa.Integer(), nullable=False),
    sa.Column('secuencial_lectura', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('tiene_alcantarillado', sa.Boolean(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('creado_por_id', sa.Integer(), nullable=True),
    sa.Column('actualizado_por_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['acometida_id'], ['acometidas.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['actualizado_por_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['creado_por_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['propietario_id'], ['ciudadanos.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['responsable_pago_id'], ['ciudadanos.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cuentas_id'), 'cuentas', ['id'], unique=False)
    op.create_table('historial_medidor_cuenta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cuenta_id', sa.Integer(), nullable=False),
    sa.Column('medidor_id', sa.Integer(), nullable=False),
    sa.Column('fecha_instalacion', sa.Date(), nullable=False),
    sa.Column('fecha_retiro', sa.Date(), nullable=True),
    sa.Column('lectura_inicial', sa.Integer(), nullable=False),
    sa.Column('lectura_retiro', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('creado_por_id', sa.Integer(), nullable=True),
    sa.Column('actualizado_por_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['actualizado_por_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['creado_por_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['cuenta_id'], ['cuentas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['medidor_id'], ['medidores.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historial_medidor_cuenta_id'), 'historial_medidor_cuenta', ['id'], unique=False)
    op.create_table('historial_tarifa_cuenta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cuenta_id', sa.Integer(), nullable=False),
    sa.Column('tipo_tarifa', sa.String(length=50), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('creado_por_id', sa.Integer(), nullable=True),
    sa.Column('actualizado_por_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['actualizado_por_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['creado_por_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['cuenta_id'], ['cuentas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historial_tarifa_cuenta_id'), 'historial_tarifa_cuenta', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_historial_tarifa_cuenta_id'), table_name='historial_tarifa_cuenta')
    op.drop_table('historial_tarifa_cuenta')
    op.drop_index(op.f('ix_historial_medidor_cuenta_id'), table_name='historial_medidor_cuenta')
    op.drop_table('historial_medidor_cuenta')
    op.drop_index(op.f('ix_cuentas_id'), table_name='cuentas')
    op.drop_table('cuentas')
    op.drop_index(op.f('ix_acometidas_id'), table_name='acometidas')
    op.drop_index('idx_acometidas_geometria', table_name='acometidas', postgresql_using='gist')
    op.drop_table('acometidas')
    op.drop_index(op.f('ix_predios_id'), table_name='predios')
    op.drop_index(op.f('ix_predios_clave_catastral'), table_name='predios')
    op.drop_index('idx_predios_geometria', table_name='predios', postgresql_using='gist')
    op.drop_table('predios')
    op.drop_index(op.f('ix_medidores_serie'), table_name='medidores')
    op.drop_index(op.f('ix_medidores_id'), table_name='medidores')
    op.drop_table('medidores')
    # ### end Alembic commands ###
