"""Add tipo_proceso_id to ProcesoContratacion

Revision ID: b80aa431f85d
Revises: 5cedf87db14a
Create Date: 2026-03-07 23:56:22.049799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b80aa431f85d'
down_revision: Union[str, Sequence[str], None] = '5cedf87db14a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('plantilla_documento', 'anio',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('2026'),
               schema='contratacion')
    op.alter_column('plantilla_documento', 'version',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'),
               schema='contratacion')
    op.alter_column('plantilla_documento', 'is_activa',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'),
               schema='contratacion')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('plantilla_documento', 'is_activa',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'),
               schema='contratacion')
    op.alter_column('plantilla_documento', 'version',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'),
               schema='contratacion')
    op.alter_column('plantilla_documento', 'anio',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('2026'),
               schema='contratacion')
    # ### end Alembic commands ###
