"""Add datos_formulario to proceso_contratacion

Revision ID: d03c2197b679
Revises: 9c37cbf59551
Create Date: 2026-03-08 10:50:18.766182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd03c2197b679'
down_revision: Union[str, Sequence[str], None] = '9c37cbf59551'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proceso_contratacion', sa.Column('datos_formulario', postgresql.JSONB(astext_type=sa.Text()), nullable=True), schema='contratacion')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proceso_contratacion', 'datos_formulario', schema='contratacion')
    # ### end Alembic commands ###
