"""Arquitectura Genealogia Reforma PAC

Revision ID: d7c5d8e774cb
Revises: 0d7158ce8ae4
Create Date: 2026-03-09 22:44:40.076785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7c5d8e774cb'
down_revision: Union[str, Sequence[str], None] = '0d7158ce8ae4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historico_reforma_pac',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pac_anual_id', sa.Integer(), nullable=False),
    sa.Column('numero_reforma', sa.Integer(), nullable=False),
    sa.Column('fecha_reforma', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolucion_administrativa', sa.String(length=255), nullable=True),
    sa.Column('descripcion_justificacion', sa.Text(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('creado_por_id', sa.Integer(), nullable=True),
    sa.Column('actualizado_por_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['actualizado_por_id'], ['configuracion.usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['creado_por_id'], ['configuracion.usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pac_anual_id'], ['contratacion.pac_anual.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='contratacion'
    )
    op.create_index(op.f('ix_contratacion_historico_reforma_pac_id'), 'historico_reforma_pac', ['id'], unique=False, schema='contratacion')
    op.create_table('genealogia_monto_pac',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('historico_reforma_id', sa.Integer(), nullable=False),
    sa.Column('item_origen_id', sa.Integer(), nullable=True),
    sa.Column('item_destino_id', sa.Integer(), nullable=True),
    sa.Column('monto_transferido', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['historico_reforma_id'], ['contratacion.historico_reforma_pac.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_destino_id'], ['contratacion.item_pac.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['item_origen_id'], ['contratacion.item_pac.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    schema='contratacion'
    )
    op.create_index(op.f('ix_contratacion_genealogia_monto_pac_id'), 'genealogia_monto_pac', ['id'], unique=False, schema='contratacion')
    op.drop_index(op.f('ix_administracion_permissions_id'), table_name='permisos', schema='configuracion')
    op.drop_index(op.f('ix_administracion_permissions_nombre_permiso'), table_name='permisos', schema='configuracion')
    op.create_index(op.f('ix_configuracion_permisos_id'), 'permisos', ['id'], unique=False, schema='configuracion')
    op.create_index(op.f('ix_configuracion_permisos_nombre_permiso'), 'permisos', ['nombre_permiso'], unique=True, schema='configuracion')
    op.drop_index(op.f('ix_administracion_roles_id'), table_name='roles', schema='configuracion')
    op.drop_index(op.f('ix_administracion_roles_nombre_rol'), table_name='roles', schema='configuracion')
    op.create_index(op.f('ix_configuracion_roles_id'), 'roles', ['id'], unique=False, schema='configuracion')
    op.create_index(op.f('ix_configuracion_roles_nombre_rol'), 'roles', ['nombre_rol'], unique=True, schema='configuracion')
    op.drop_index(op.f('ix_administracion_users_cedula'), table_name='usuarios', schema='configuracion')
    op.drop_index(op.f('ix_administracion_users_correo'), table_name='usuarios', schema='configuracion')
    op.drop_index(op.f('ix_administracion_users_id'), table_name='usuarios', schema='configuracion')
    op.create_index(op.f('ix_configuracion_usuarios_cedula'), 'usuarios', ['cedula'], unique=True, schema='configuracion')
    op.create_index(op.f('ix_configuracion_usuarios_correo'), 'usuarios', ['correo'], unique=True, schema='configuracion')
    op.create_index(op.f('ix_configuracion_usuarios_id'), 'usuarios', ['id'], unique=False, schema='configuracion')
    sa.Enum('ACTIVO', 'ELIMINADO_POR_REFORMA', 'MODIFICADO_POR_REFORMA', name='status_item_pac').create(op.get_bind(), checkfirst=True)
    op.add_column('item_pac', sa.Column('status', sa.Enum('ACTIVO', 'ELIMINADO_POR_REFORMA', 'MODIFICADO_POR_REFORMA', name='status_item_pac'), nullable=False), schema='contratacion')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item_pac', 'status', schema='contratacion')
    op.drop_index(op.f('ix_configuracion_usuarios_id'), table_name='usuarios', schema='configuracion')
    op.drop_index(op.f('ix_configuracion_usuarios_correo'), table_name='usuarios', schema='configuracion')
    op.drop_index(op.f('ix_configuracion_usuarios_cedula'), table_name='usuarios', schema='configuracion')
    op.create_index(op.f('ix_administracion_users_id'), 'usuarios', ['id'], unique=False, schema='configuracion')
    op.create_index(op.f('ix_administracion_users_correo'), 'usuarios', ['correo'], unique=True, schema='configuracion')
    op.create_index(op.f('ix_administracion_users_cedula'), 'usuarios', ['cedula'], unique=True, schema='configuracion')
    op.drop_index(op.f('ix_configuracion_roles_nombre_rol'), table_name='roles', schema='configuracion')
    op.drop_index(op.f('ix_configuracion_roles_id'), table_name='roles', schema='configuracion')
    op.create_index(op.f('ix_administracion_roles_nombre_rol'), 'roles', ['nombre_rol'], unique=True, schema='configuracion')
    op.create_index(op.f('ix_administracion_roles_id'), 'roles', ['id'], unique=False, schema='configuracion')
    op.drop_index(op.f('ix_configuracion_permisos_nombre_permiso'), table_name='permisos', schema='configuracion')
    op.drop_index(op.f('ix_configuracion_permisos_id'), table_name='permisos', schema='configuracion')
    op.create_index(op.f('ix_administracion_permissions_nombre_permiso'), 'permisos', ['nombre_permiso'], unique=True, schema='configuracion')
    op.create_index(op.f('ix_administracion_permissions_id'), 'permisos', ['id'], unique=False, schema='configuracion')
    op.drop_index(op.f('ix_contratacion_genealogia_monto_pac_id'), table_name='genealogia_monto_pac', schema='contratacion')
    op.drop_table('genealogia_monto_pac', schema='contratacion')
    op.drop_index(op.f('ix_contratacion_historico_reforma_pac_id'), table_name='historico_reforma_pac', schema='contratacion')
    op.drop_table('historico_reforma_pac', schema='contratacion')
    # ### end Alembic commands ###
