"""Creacion modulo contratacion

Revision ID: e17a9b119602
Revises: 0c98f2cd13eb
Create Date: 2026-03-08 02:55:23.542140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e17a9b119602'
down_revision: Union[str, Sequence[str], None] = '0c98f2cd13eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proceso_contratacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_proceso', sa.String(length=50), nullable=False),
    sa.Column('nombre_proyecto', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('creado_por_id', sa.Integer(), nullable=True),
    sa.Column('actualizado_por_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['actualizado_por_id'], ['administracion.users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['creado_por_id'], ['administracion.users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['usuario_id'], ['administracion.users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    schema='contratacion'
    )
    op.create_index(op.f('ix_contratacion_proceso_contratacion_codigo_proceso'), 'proceso_contratacion', ['codigo_proceso'], unique=True, schema='contratacion')
    op.create_index(op.f('ix_contratacion_proceso_contratacion_id'), 'proceso_contratacion', ['id'], unique=False, schema='contratacion')
    op.create_table('tipo_proceso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('creado_por_id', sa.Integer(), nullable=True),
    sa.Column('actualizado_por_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['actualizado_por_id'], ['administracion.users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['creado_por_id'], ['administracion.users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='contratacion'
    )
    op.create_index(op.f('ix_contratacion_tipo_proceso_id'), 'tipo_proceso', ['id'], unique=False, schema='contratacion')
    op.create_table('plantilla_documento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('ruta_archivo_docx', sa.String(length=255), nullable=False),
    sa.Column('tipo_proceso_id', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('creado_por_id', sa.Integer(), nullable=True),
    sa.Column('actualizado_por_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['actualizado_por_id'], ['administracion.users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['creado_por_id'], ['administracion.users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tipo_proceso_id'], ['contratacion.tipo_proceso.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='contratacion'
    )
    op.create_index(op.f('ix_contratacion_plantilla_documento_id'), 'plantilla_documento', ['id'], unique=False, schema='contratacion')
    op.create_table('documento_generado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proceso_contratacion_id', sa.Integer(), nullable=True),
    sa.Column('plantilla_id', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('datos_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ruta_archivo_generado', sa.String(length=255), nullable=False),
    sa.Column('fecha_generacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('creado_por_id', sa.Integer(), nullable=True),
    sa.Column('actualizado_por_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['actualizado_por_id'], ['administracion.users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['creado_por_id'], ['administracion.users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['plantilla_id'], ['contratacion.plantilla_documento.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['proceso_contratacion_id'], ['contratacion.proceso_contratacion.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='contratacion'
    )
    op.create_index(op.f('ix_contratacion_documento_generado_id'), 'documento_generado', ['id'], unique=False, schema='contratacion')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contratacion_documento_generado_id'), table_name='documento_generado', schema='contratacion')
    op.drop_table('documento_generado', schema='contratacion')
    op.drop_index(op.f('ix_contratacion_plantilla_documento_id'), table_name='plantilla_documento', schema='contratacion')
    op.drop_table('plantilla_documento', schema='contratacion')
    op.drop_index(op.f('ix_contratacion_tipo_proceso_id'), table_name='tipo_proceso', schema='contratacion')
    op.drop_table('tipo_proceso', schema='contratacion')
    op.drop_index(op.f('ix_contratacion_proceso_contratacion_id'), table_name='proceso_contratacion', schema='contratacion')
    op.drop_index(op.f('ix_contratacion_proceso_contratacion_codigo_proceso'), table_name='proceso_contratacion', schema='contratacion')
    op.drop_table('proceso_contratacion', schema='contratacion')
    # ### end Alembic commands ###
