"""Modulo PAC y Nexo MM

Revision ID: e6ac70f05d87
Revises: cb36dd6b02a6
Create Date: 2026-03-09 20:31:09.550086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6ac70f05d87'
down_revision: Union[str, Sequence[str], None] = 'cb36dd6b02a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
